### ISSUE TITLE
A second option for position for the mercenary post or barracks for AIs

### ISSUE THREAD

**Issue by PitchNeeded** [Sh0wdown/UnofficialCrusaderPatch#151]
I have played some maps only to discover sometimes that some AIs with big castles such as Wolf, Emir, Saladin or Frederick can't place their mercenary post or barracks. It would be good if it could be made so that they had a second choice of position to place these buildings if the original position in their AIV couldn't be built upon.

**Comment by J0J0Jo** [comment]
If this could be implemented it would be fantastic if the AI could choose the secondary spot for its barracks if it is destroyed at least X times in Y minutes. 
It would allow castle where the barracks are placed in the line of fire (e.g. where it constantly gets destroyed by catapults) to remain viable.

**Comment by Sh0wdown** [comment]
I think that's way to complex, as I would have to add quite some code to both the game and its editor binaries.

**Comment by Heroesflorian** [comment]
@Sh0wdown would it then be possible to place the barracks _somewhere_ "randomly" if the AI does not have one as it couldn't place the one from the AIV due to lack of space? 
When the AI has no AIV at all, it also places certain buildings (including barracks) more or less randomly near the keep / where there is space, so possibly there is some code for that available that could be used?
