### ISSUE TITLE
Frage hinsichtlich der Steuerung

### ISSUE THREAD

**Issue by StrongholdFan** [Sh0wdown/UnofficialCrusaderPatch#16]
Frage an den Entwickler des Patches: Ich es theoretisch möglich, dass man die Steuerung verändert? Sprich, dass man bspw. mit WASD navigieren kann, anstatt nur per Pfeiltasten? Oder dass man neue Hotkeys einfügt, wie bspw. Speichern auf F5 und Laden auf F9 oder ähnliches? Danke. :)

**Comment by Panaminion** [comment]
First of all: Your patch is just (not exaggerating) incredible, hats off! :) I hope you dont get discouraged by all the new ideas here and its okay to throw another at you ;-) : 
I know it would be very hard to incoperate something like an autosell-feature (since this would need somekind of overlay). I was thinking maybe instead we could get a few hotkeys to sell of e.g. stone, wood, iron, beer (which is what mostly cloggs up the stock-pile) "just by the push of a button". This might help greatly with the flow of play during an attack where you need to sell of as fast as possible to stay focussed.
(I hoped that this might be feasible since you could influence the Ai buying, but of course the player might not buy "the same-way")

**Comment by Sh0wdown** [comment]
Wird im nächsten Release dabei sein.
