### ISSUE TITLE
Wolf - Arabian Archers on towers and walls

### ISSUE THREAD

**Issue by ByBurton** [Sh0wdown/UnofficialCrusaderPatch#165]
As mentioned in issue #5  , the Wolf was meant to have Arabian bowmen on his towers and walls, as can be seen in the AIV files.
Would be awesome, if that could be restored / done.

**Comment by PitchNeeded** [comment]
The Wolf uses Arabian archers to defend farms though, so it must be made sure he can still send enough to defend them.

And speaking of archers on walls, can we finally have a King Phillip that posts more than 1 or 2 archers at one spot on his towers :D And Sultan having a reserve of Arabian archers on his keep rather than sending all of them away during sieges.

**Comment by Heroesflorian** [comment]
If I recall correctly, the Caliph also had slinger spots, right?

**Comment by Sh0wdown** [comment]
Possible with AIC edits now.
