### ISSUE TITLE
AI raids bug with 'AIs attack nearest castle'

### ISSUE THREAD

**Issue by PitchNeeded** [Sh0wdown/UnofficialCrusaderPatch#167]
Played a game as a human player on Last Stand map at the top left corner with two allies at the bottom right and the rest of the players were enemy AIs (including the player in the centre). I enclosed all my industries and the two AIs opposite me at the top right of the map who were attacking me didn't send raids to any enemy building at all, (and this was a particular problem as one of those two AIs was the best AI raider in the game, Marshall), even to my southern allies' farms, mines and quarries which were outside their castles. Did another match with Emir being one of my closest enemies and he also didn't raid any of my southern allies industries either with his Arabian swordsmen. Only sent his raid towards me when there was a breach in my castle wall.

It seems that on 'AI's attack nearest enemy' mode, even their raids only seem to attack the nearest enemy too, and if their nearest enemy is a human players' castle which is completely enclosed they won't raid anyone at all. It would be good if this bug with 'AIs attack nearest castle mode' was fixed so that the AI could still raid other enemy AIs if the enemy opposite is an unraidable human player who has enclosed all their industries.

**Comment by Heroesflorian** [comment]
@PitchNeeded from what you described so far, I doubt this is an actual bug with the "nearest target" patch option: The AI generally only raids their current attack target. 
The AI can also send defensive patrols to defend their workers, and those can possibly fight other opponents, but conscious raiding and attacking always is done exclusively to the attack target, and if the attack target does not change (most gold or least troops is rather volatile, nearest opponent only changes when someone dies), nor does the raiding target. 

Of course, it might be cool (at least in theory) to have raiders attack e.g. walls and other defenses instead when there are no unprotected / attackable buildings available outside the walls. In practice, of course this could be potentially exploited by human players (e.g. put moat around your walls, with one separate blob of walls in front of your actual wall in one place, in range of fire throwers or crosbowmen, to lure in and destroy raiding troops who try to attack the "bait wall"). 
Making the AI switch raiding target (to differ from the general attack target) when the current attack target has no "raidable" buildings might also be an option, but that arises the question of what criteria to use for picking a new raiding target, and also possibly changes overall game balance more than intended. 

Also, currently, the AI just stops raiding in that case, and even lets their raiding units stand in place right in front of the enemy castle if they happen to have destroyed the last accessible exterior building right there. Just retreating their raiding units instead of letting them stand there to die would be quite helpful.

**Comment by PitchNeeded** [comment]
Yes, and I do think it is good that AIs generally raid the same castle they are attacking (as with good raiders such as Phillip, Marshall or Emir they can send raids in at the same time as their siege to destroy buildings of the same enemy).

I would also like to see Emir's raiding Arabian swordsmen be able to finish off weak enemies directly, as they can often be strong enough to do, and so it makes sense if they were passing by an enemy AI that had an enclosed wall to their castle but were militarily weak (and had sent their 'panicking' message about the enemy outside their walls), that they would switch from destroying outside buildings to trying to breach the castle wall and then going directly for the enemy lord.

**Comment by Krarilotus** [comment]
redundancy with #157, you can discuss further details there
