### ISSUE TITLE
AI food buying

### ISSUE THREAD

**Issue by PitchNeeded** [Sh0wdown/UnofficialCrusaderPatch#17]
This patch is amazing, I didn't think it was possible to change AI behaviour......

I have a suggestion to try and improve some of the AI's economies a little even in their original castles......as you know most AIs buy in other food varieties every so often even if they have food. It would be good to have more food variety for AIs, for example Emir buying in 10 apples and 10 cheese instead of his standard 20 apples and Sultan can buy 5 cheese, 5 apples, 5 meat and 5 bread instead of just buying apples. Even Rat could buy in 5 bread, 5 meat and 5 cheese instead of just apples. This would allow them to increase their tax rate. :)

**Comment by PitchNeeded** [comment]
Yes I suppose rat's character would be too stupid to think about the benefits of food variety and for Sultan, less woodcutters (about 7 instead of his current 15) and farms instead and a few iron mines! Of course the original castles should be changed slightly (a few more houses) to account for this, for those who still like using the original castles!

**Comment by ByBurton** [comment]
I disagree, I think the Sultan is fine. He should not be buffed... And if, just the tiniest little bit, he is in a good spot right now. He is meant to be very easy to beat.

**Comment by PitchNeeded** [comment]
OK then, just one more quarry with 2 ox tethers (5 people) in place of 5 of his woodcutters then might be a good balanced solution for Sultan, a slightly better economy but still easy to beat as intended!

**Comment by PitchNeeded** [comment]
You are probably right, and economies of AIs can be easily improved by building new castles for them with more production, they are probably fine at the minute. However I still think it should be modified to improve at least some of the AIs economies (maybe not Rat's though as you say 😄 ) by buying in more food types.

Wazir and Emir buying in 10 cheese and 10 apples instead of 20 apples would be better for them for 2 reasons: increased food variety and therefore taxes, plus if they run out of food it costs less to replenish their supplies as they can choose to replenish just the 10 apples or just the 10 cheese!  Caliph also I think could with buying in 10 cheese and 10 apples instead of just apples. Phillip buys in 20 cheese, 20 apples and 20 bread, he would be better buying in 15 apples, 15 cheese, 15 bread and 15 meat instead, so he can boost his taxes!

**Comment by Heroesflorian** [comment]
Also, I wouldn‘t mind the Rat buying cheese at least - I mean, come on, Rat and Cheese, that‘s a no-brainer!

**Comment by PitchNeeded** [comment]
> Buying food despite generally having excess food, just to maintain food variety - in this case, selling e.g. 5 bread and buying 5 apples results in a net loss of gold through the trading, which may or may not be made up for by slightly higher taxes due to the +1 extra popularity for a couple seconds.

Yeah I have changed my mind now about Wazir, and actually now think he should be changed again to **just buy bread if his granary is empty or nearly empty** rather than buying in 20 apples every so often for food variety. Two reasons: Wazir relies a lot on selling bread for his economy to flourish, and buying in apples every so often will cost him more than he would recoup from the +1 popularity boost and 2. Wazir is an evil lord who wouldn't care about giving his people much food variety anyway. 😃 

> And for the Sultan, 4 food types would really fit him well I’d say, because 1. it’s efficient for him who buys food anyway (and his economy is weak enough to need every little push it can get), and 2. it also fits his character quite well, I’d say: He likes feasting and relaxing in his flower-filled palace more than battling, and he does whatever he can in order to make his people happy, not caring profane issues such as about money and costs for luxurious things like elaborate meals, home comfort or ornamental decorations when he is busy meditating or studying poetry.

Yeah that's what I was thinking. Just thinking there, maybe just 3 food types rather than 4 food types for Sultan though as +5 fear factor and +3 food variety would allow him to use -8 for taxes. 4 food types would create +9 for taxes and that extra +1 isn't very useful for him.

**Comment by ByBurton** [comment]
I disagree. The AI uses taxing a lot to get  down to ~50 popularity and gaining some extra money doing that, and then let it recover a bit again.
Which means a +1 goes a loooong way.

**Comment by PitchNeeded** [comment]
You are right. So Sultan would benefit from buying all four food types. Still not sure though about whether or not Wazir should just buy bread if he is lacking and not buy apples and also whether Emir should switch to buying 10 apples and 10 cheese instead of 20 apples.

**Comment by Heroesflorian** [comment]
Regarding the "popularity lowering tax tricks" of the AI, I generally hate those, though. 

Not because I think it would be unfair or OP in anyway, but rather the opposite... the AI even does that down to -24 taxes if they can, which is downright awfully inefficient in terms of gold/popularity, and the AI also goes down to 50 popularity when having TONS of gold, limiting the own recruiting speed (lower popularity = slower peasant spawning). 
Furthermore, the AI could just as well move between 90 and 95 popularity (or 80 and 100 at most), to avoid peasant shortage and situations where it has about 50 popularity, and now the granary goes empty/destroyed or an inn runs out of ale or whatever else, and suddenly it goes below 50 and needs to cut taxes a lot in order to get back up... 

Anyway, yeah, Wazir without apples might be better. Although who knows... his negative fear factor combined with no ale or religion means his only ways to get his popularity right are either bigger rations, multiple food types, or negative taxes... so at -5 fear factor, he could use extra rations (+4) combined with no taxes (+1) and bread & apples (+1) to raise popularity (total of +1), and switch to low taxes (-2) to lower it (total of -2) and make extra tax money (which even is super efficient in terms of gold/popularity compared to the higher tax rates). 

Although, knowing the AI, I'd bet he rather goes all out with double rations and higher taxes anyway...

**Comment by ByBurton** [comment]
> Although, knowing the AI, I'd bet he rather goes all out with double rations and higher taxes anyway...

They still manage to earn tons of money though. I am always shocked how much enemies like Saladin, Wolf, Emir or Wazir earn. So it can not be that bad now, can it?

**Comment by PitchNeeded** [comment]
>  Anyway, yeah, Wazir without apples might be better. Although who knows... his negative fear factor combined with no ale or religion means his only ways to get his popularity right are either bigger rations, multiple food types, or negative taxes... **so at -5 fear factor**

He rarely if ever uses -5 fear factor from what I observe, -3 is what he commonly uses.

> They still manage to earn tons of money though. I am always shocked how much enemies like Saladin, Wolf, Emir or Wazir earn. So it can not be that bad now, can it?

Although Wazir and Emir (and Nizar too) do have faster recruitment speeds than Saladin, Wolf or Frederick and so do tend to deplete their gold quicker when they start with 40,000 gold.

**Comment by Heroesflorian** [comment]
> They still manage to earn tons of money though. I am always shocked how much enemies like Saladin, Wolf, Emir or Wazir earn. So it can not be that bad now, can it?

Well yeah, but so can a human player... difference being, a good human player would simply end the match before having 250k gold reserves, usually. 
And ofc, human players also sometimes have their stockpiles filled up because they focus more on making senseful troop movements and siege attacks, which the AI is just not really capable of in most situations, and hence have no real need for economic efficiency in the later game. 

> He rarely if ever uses -5 fear factor from what I observe, -3 is what he commonly uses.

-3 fear factor instead of -5 then makes it possible to stay on -2 taxes for a total of 0 popularity with the setup as mentioned previously... not bad either, imho. 

> Even Pig too if he is in a good economic position, can make a lot of money, I notice, he started one match I was playing against a few AI lords on 40,000 gold and ended up with over 150,000 gold iirc even though he was attacking me frequently with lots of macemen!

Pig's economy is really situational, though... sometimes it works out fairly well, and sometimes it is just "meh". A good Saladin, Frederick or Abbot can make many times more gold.
