### ISSUE TITLE
AIs using portable shields and portable shield speed

### ISSUE THREAD

**Issue by PitchNeeded** [Sh0wdown/UnofficialCrusaderPatch#175]
It has been proposed on here that AIs could use portable shields when they attack, which would be great I think, but the problem is the speed of them. It was proposed that they could be made slower (as it is heavy to carry a portable shield), which would certainly help them protect advancing crossbowmen when advancing (and benefit Wolf, Pig, Sheriff and Frederick), but if we wanted the Arabian AIs to use them with their horse archers (which would be a good strategy that many human players use) that would be a problem.

**Comment by Monsterfisch** [comment]
easy solution have the ai select and move the shields with the units you want them to be paired with which will result in them walking at the same speed or max speed of the shield (i advise for making shields slowers overall however as they somehow become faster than their no shield carrying counterpart which is ridiculed especially since they can almost keep up with horses?)

**Comment by Krarilotus** [comment]
#42 and #111 cover these topics. Closed because of redundancy.
