### ISSUE TITLE
Heilung aus Crusader Extreme

### ISSUE THREAD

**Issue by luwer1** [Sh0wdown/UnofficialCrusaderPatch#18]
Wäre es möglich den Code des Heilungszaubers aus Crusader Extreme zu verwenden, um im Umkreis der Apotheke in gewissen Abständen Truppen heilen zu können ?

**Comment by ByBurton** [comment]
Aber auch bitte nur, wenn keine Gegner in der Nähe sind.... Fände ich extrem dämlich, wenn man jemanden angreift, und dessen Verteidiger werden dauernd ruckzuck hochgeheilt..

**Comment by PitchNeeded** [comment]
I don't think it would be a good idea, it would make it too easy for the player against AIs who use horse archers/fire ballistae in their attacks if their injured tower archers and crossbowmen were auto-healed between AI attacks due to being in range of an apothecary. Cumulative damage on tower missile units over several AI attacks from horse archers/fire ballistae really causes a lot of damage and added costs to replace fallen archers or crossbowmen if you choose like me to make the game harder by not using portable shields on towers. :smiley:

**Comment by Heroesflorian** [comment]
Hmm... in theory - the whole feature might just be infeasible due to an excessive amount of required work without source code access anyway - it could work if the radius is quite small and only affects troops on the ground (like plague and fire). 
If the defender has to move around his defensive troops, remove them from his towers to place them next to apothecaries in small groups, move them back up later, etc., then this makes it considerably harder to excessively "abuse" apothecary healing for "OP defenses", as it results in a "cost" for players using healing: Management effort as well as temporary vulnerability due to tower garrison troops being moved away and onto the ground. 
That would mak you really think twice about whether you really wanna try to heal up all the time, or rather focus on other things - sending off half your defensive troops for healing, and then getting hit by a massive siege attack while you are re-placing farms elsewhere and notice the attack too late, or getting beaten up by a bunch of hostile knights massacring a bunch of your archers outside that are trying to heal... that is quite some risk. 
And yes, one could still try to wall off half of the map and spam dozens of apothecaries behind your frontline defenses, covering a good portion of your castle area with those buildigs, for healing up many units rather quickly, but then again one probably would be better off just covering that area in economic builidings to generate enough additional gold to replace one's troop losses manifold.

**Comment by ByBurton** [comment]
It all depends on how strong / fast the heal is, how big the radius, and if it can heal units on top of walls / towers as well.

If the healing does not affect units on walls and towers, and heals rather slowly in a, say 3m² area around the apothecary it would be pretty balanced I think.
Still, I don't think that is a necessary feature, especially because apothecaries are not really used by any computer enemy besides the Wazir I think.
Still, I love that he uses them :D.

**Comment by Sh0wdown** [comment]
https://github.com/Sh0wdown/UnofficialCrusaderPatch/releases/tag/v2.09 lets the healer actually heal people.
