### ISSUE TITLE
KI Castle Defence 

### ISSUE THREAD

**Issue by Derever** [Sh0wdown/UnofficialCrusaderPatch#182]
Would it be possible to enable the KI to use ALL there archers and other “range units” on the wall and towers to defend while prepairing for there next attack? This would also make fights human against KI a lot more attractive especially in combination with all the new amazing castle designs.

**Comment by PitchNeeded** [comment]
It might be a good idea for some of the lords, but wouldn't work for Phillip and Nizar who don't use any ranged units in their attacks or Wazir who (apart from a few fire throwers) only uses horse archers as ranged units in his attacks (although he could always put horse archers on top of his big towers :D).

**Comment by Derever** [comment]
Absolutely agreed!
Maybe it would be possible to just raise the amount of defensive range troups in total with a slider and then the AI either just puts more people on the towers and walls or if that’s possible from the programming part even uses some of the attack troups temerorarly for that it, they have any.

**Comment by PitchNeeded** [comment]
Another matter concerning castle defence: I think Emir, Wazir, Saladin and Sheriff would benefit from having some slingers on their towers alongside their current missile troops.

**Comment by Derever** [comment]
I would like to see that also for the visual purposes.

**Comment by PitchNeeded** [comment]
Yes Emir and Sheriff in particular could benefit from slingers, for Sheriff the slingers would counteract the low rate of fire from his crossbowmen and slingers and crossbowmen are a good defensive combination, and for Emir, the slingers would allow him to do more damage to heavily armoured troops attacking his walls.

Saladin and Wazir may as well have them too, they are cheap to hire after all and do some good damage to heavily armoured troops over time due to their high fire rate.

Slingers also are good to counterattack horse archers who get too close to the walls!

**Comment by PitchNeeded** [comment]
I would also like to see AIs use portable shields on their towers (a tactic many human players use) if possible too!

**Comment by PitchNeeded** [comment]
I think it would make it much slower for the Arabian AIs to siege if their horse archers patrolled between sieges, as they would be at risk of being killed by enemies, particularly by AIs that raid with knights or those that use lots of crossbowmen to guard their farms (Pig, Sheriff, Frederick).

Also there is a risk that the horse archers could be sent to patrol a farm within range of an enemy tower (that happens already with Wazir sometimes and isn't great tactically).

**Comment by Monsterfisch** [comment]
That's why I mentioned the horse-archers beeing bit iffy here. Its really something you can't predict so much at this point as horse archers are good harassment units, to begin with especially when they are constantly moving which could be possible this way as they would patrol between the different patrols aka never really stay still in one place with a current patrol as they would immediately after arriving move to the next one. in my book that would make the Arabic lords more potent overall.

**Comment by PitchNeeded** [comment]
Maybe! Perhaps if this was implemented, there should be a certain range set so the horse archers don't go to farms or economic buildings too far away from the castle.

**Comment by ByBurton** [comment]
This can be achieved via the aic files.
