### ISSUE TITLE
Healer Feedback

### ISSUE THREAD

**Issue by Monsterfisch** [Sh0wdown/UnofficialCrusaderPatch#192]
First of all brilliant addition finally Healers are not just a massive and expensive decoration building anymore ^^ literally gave me a goosebumps reading about the change xD

That being said there is some more room for improvement here to make it feel like a truly worthy utility in the castle.
So here is a short list with changes I would propose to make the Healer feel like a proper feature (sorted by relative urgentness)

- [ ] healers should ignore units that are in unreachable locations (like units that remained after a, with walls surrounded, tower got destroyed without turning into a ruin keeping the units alive same for units that got stuck in locations because of the terrain and impossible to build towers and the like) otherwise they get stuck in a enter and exit building loop 

- [ ] Since the building itself is pretty expensive and there are many people to heal around I would suggest that we get 2 healers per building instead of one (this would depend on how effective or not the healer would be if his target-finding was improved that is [next paragraph]). This would substitute as a quick and dirty way to increase his effectiveness in the short-term. 

- [ ] Due to the way the healer seeks out the closest injured person it really matters where you place down the building itself making the healer ineffective when he is placed in a castle with a single exit in the front for example. That results in the Healer happily walking past injured units while trying to go heal injured people behind the castle for example https://i.imgur.com/C8ZyZyd.jpg
here I would like to suggest that the Healer stops when he is close to an injured unit while walking to his current target heals them as far as he can and then selects a new target from that location if he still has heals available.

- [ ] I would also suggest increasing the range of the building as it seems as if the healer will only seek out people around 20 tiles away (guessing) again the building is rather costly and large so it should be able to cover the entire castle (for the player that would be the entire area where the player can build defence structures) in my humble opinion ;)

- [ ] Not sure if this is already a thing and I am sure testing would take a lot longer than simply asking here, but it would be nice if the Healer would change his healing ability depending on the fear factor as well so when the fear factor is high he would stroll less but also heal less with each healing and in turn would stroll more but also heal more at a time when fear factor is positive. In conjunction with this, it could be considered to give the healer limited amounts of heals per walk so like he can heal 6 or more times per walk for example before he has to return (while testing it seemed like it was more time based on how many heals he was able to do per run). This aspect could than also be influenced by the fearfactor where the healer would have slightly less healingpacks with him if fearfactor is high as they are better quality so to speak. 

- [x] referring to #187 it could also be nice to maybe give the healer an area of effect of around 2 tiles around him when treating sick/poisoned people if the poison aspect mentioned here is considered/implemented. (again depending on target choosing and or amount of healers per building.
Giving units and peasants an immunity against desease right after getting healed or beeing treated from desease would also be nice here.

**Comment by ByBurton** [comment]
My feedback: I love the new mechanic, but units that are further away from the castle, like economy defenders, are not being healed at all (even if there are no other injured units anywhere nearer). Instead the healers just walk out of the building, and in weird routes around and back in again.

**Comment by Monsterfisch** [comment]
just noticed that one too and added it to the list =) seems like healers have a detection radius of about 20/30 tiles around the building which in my screenshot doesn't even reach the injured oilpot engineer whos being denied healing entirely.

**Comment by Panbutt** [comment]
Yeah I disagree on an area of effect as well. I like that the healer treats wounded soldiers personally, adds a nice touch of atmosphere.

I think this addition is amazing. This actually something I've wanted for ages, for apothecaries to actually be very very useful and worth getting. I haven't tested it fully, but can the Lord be healed as well? It would be interesting and helpful for AIs/Players coming back from the brink of death. Granted it'd likely take a very long time considering how beefy Lords are but I think that's perfectly fine.

**Comment by ByBurton** [comment]
> I would simply suggest increasing the healing amount instead
No, the healing amount is fine in my opinion. Maybe increase the speed of the healer instead?

> The current range is 40 "stronghold units". I just didn't want them to walk into an enemy's castle to heal an assault army. But sure, I can easily increase it.
Well, you should check how much the max. radius of a castle can be, and set it to that.
There is a point at which you can no longer place defenses. I would set the radius to that.

**Comment by ByBurton** [comment]
> but can the Lord be healed as well? It would be interesting and helpful for AIs/Players coming back from the brink of death. Granted it'd likely take a very long time considering how beefy Lords are but I think that's perfectly fine.

If you want to make sure the lord gets healed, try and get him hurt, and then let him stand next to a healer.

**Comment by Monsterfisch** [comment]
That's the thing I personally quite like that the amount isn't so high/instant for the healing as it makes the healing feel reasonable instead of drink op heal potion kind of deal. But either direction should be fine really as long as the result is an improvement of the effectiveness.

I wouldn't be worried about them trying to heal assault armies too much the healer itself doesn't cost the player anything to recruit and since he heals the closest units first he would have his hands full before he marches out into enemy territory after all =) (at least in theory)

The idea behind the area of effect would be mostly reserved for the treating of disease and giving the people immunity to the deceased cows for a period of time but if the healer would already be doing the job well enough without Aoe I have no complains hehe

**Comment by Sh0wdown** [comment]
> can the Lord be healed as well?

Yes, but they have indeed a lot of health.

> The idea behind the area of effect would be mostly reserved for the treating of disease and giving the people immunity to the deceased cows for a period of time (consider the aoe as the healer handing out medicine to people that come to him for help so to speak) but if the healer would already be doing the job well enough without Aoe I have no complains hehe

Apothecaries already grant resistance to those plague clouds of up to 60% with 3 buildings. Should this simply be increased maybe?

**Comment by ByBurton** [comment]
> Apothecaries already grant resistance to those plague clouds of up to 60% with 3 buildings. Should this simply be increased maybe?

Nah, disease clouds are more than fine right now. They are even too weak. Just buff the clouds first, then we can see if they are too strong or not.

**Comment by Heroesflorian** [comment]
>If there are injured soldiers, civilians or animals in range, the healer seeks them out and heals them. When there are no more wounded targets in the area, he continues his usual strolls through the castle. The strolls through gardens (fear factor) and investigation of plague clouds are still part of his normal routines. With each trip, the healer performs up to five healing animations, of which each heals about 1/3 of the health of a spearman. Near targets are preferred.

If the release notes are correct, then the range limitation is intended. As such, I actually like a limited range of some sorts, as well as the single-target healing thing, especially with respect to human players. Slightly increasing the range and/or the efficiency of the healer within that range is something I'd personally see as much preferable as compared to unlimited range or a massive "full building area" range. 

Also keep in mind the healer buildings also (even in vanilla) grant a 20% damage reduction from plague clouds, so building several healers in different sections of a castle to get a higher global damage reduction (goes up to a max. of 60% iirc), and providing unit healing at different locations still makes sense if you have a larger castle and some spare gold, even if (thinking of AIV or human player build orders) one healer first, then later additional ones is probably more reasonable than building them all at once. 

Regarding the healing of further-away units (e.g. patrols) - I think a range extension to cover those units will not be feasible in general, for similar reasons as why it is not really feasible to heal your own attack army right in front of a hostile castle... also, as I see it, healing should be used selectively, or it will become OP, and hence healing units that do usually not get hurt a lot in short time makes more sense - castle defenders and other close-by troops. Some patrol archer that will likely die in the near future anyway - e.g. get shot in to death by some hostile tower ballista, get smashed by a horde of hostile macemen or similar - is not the kind of troop you want to spend your valuable healing powers on, imho. 

Regarding healing the Lord: In Crusader Extreme, the 2nd ability is an AoE healing effect, which also affects the Lord (and yes, it takes quite a while / a high number of ability casts in order to fully heal up a severely injured Lord). As such, I would support making the Lord healer-healable as well, if the amount is not excessive there either. 

Regarding the pathfinding / prioritizing issues of healers: They go for "air distance nearest first". Which can give facepalm-worthy results sometimes. But the same strategy is used throughout the game for a couple other things as well: 
E.g. woodcutters go for "air distance nearest trees first", even if that requires them to traverse the entire map to actually get there, no matter whether 2 tiles further away a directly accessible tree would be. 
Tanners also try to get the "air distance nearest cow", iirc. 
And even some units on aggressive mode sometimes show weird behavior that might have similar root causes. (I remember knights attacking the closest target available when getting shot by hostile archers, if they cannot reach those archers due to being on a wall/tower.)

So if this "air distance nearest first" can be improved upon, to provide "walking distance nearest first" or other more effective strategies, this would benefit more than just healers.

**Comment by PitchNeeded** [comment]
Good new feature. Haven't tested it out now, but what is the range and does that mean that any AIs that have healers (which I think is just Frederick, Emir and Wazir for the vanilla castles) can manage to heal their injured tower archers/crossbowmen now without the archers having to leave the tower?

**Comment by ByBurton** [comment]
@Heroesflorian But increasing the range is not a thing that will be noticeable too much. Only if there are no hurt units around the healer. And seeing healers that don't do anything with economy defenders out there that are all almost dead just seems wrong, don't you agree?
I mean, they will prioritize the nearest, so that will make more than up for it.

**Comment by Heroesflorian** [comment]
And dammit, while writing my reply, literally over half a dozen other replies came in, didn't notice the last few ones... :D 

> Apothecaries already grant resistance to those plague clouds of up to 60% with 3 buildings. Should this simply be increased maybe?

Iirc, it is currently at 20% per apothecary, up to a maximum of 60% at 3. Increasing the cap to max. 80% at 4 or 5 would be fine with me, but a steeper increase than currently, or a total cap higher than 80% doesn't make much sense imho. After all, healers also heal now, which in itself can be reason enough to have several ones throughout a larger castle. And, as others already pointed out, buffing plague clouds in general would be a precondition for really having a real benefit from the reduction in most situations. I mean, how many games you remember were affected notably by the use of plague? In SH1, plague was a lot stronger than in SHC1.

**Comment by Monsterfisch** [comment]
Totally forgot that that was their original purpose xP 
A testament to how useless healers were in the original game ...

Is the 60% resistance only applied to people that are "blessed" or overall? 
who in the hell builds 3 Apothecaries ?! ;)  depending on how disease clouds work in the future I would make it that 3 Apothecaries  grant 75% protection and 2 would provide 25% or something like that that would resemble the cost of the building a lot more as it is pretty costly (mostly looking at it from a AIV perspective here where its rough to add 3+ Apothecaries  in a reasonably sized castle/city  so it can actually be used on most maps)

**Comment by Heroesflorian** [comment]
> Good new feature. Haven't tested it out now, but what is the range and does that mean that any AIs that have healers (which I think is just Frederick, Emir and Wazir for the vanilla castles) can manage to heal their injured tower archers/crossbowmen now without the archers having to leave the tower?

Actually, iirc, about 6 out of 16 AI characters have apothecaries in their vanilla castles. (See here: https://github.com/Sh0wdown/UnofficialCrusaderPatch/issues/18#issuecomment-439227651) 
That actually makes apothecaries as common in the game as Arabian AI characters (6 out of 16 as well), with an even 3 : 3 splitting between Arabian and European characters. 

For the healer range, just see the above replies, it was written there. 

> @Heroesflorian But increasing the range is not a thing that will be noticeable too much. Only if there are no hurt units around the healer. And seeing healers that don't do anything with economy defenders out there that are all almost dead just seems wrong, don't you agree?
> I mean, they will prioritize the nearest, so that will make more than up for it.

Well, maybe... guess this is something that is worth some testing. Did anyone already test what happens if the current healing target of a healer dies? Does he retarget immediately, and based on his current position? If not, that makes "volatile" healing targets problematic - e.g. vulnerable patrols troops. 

Also, what if patrol troops move across half of the map (as they patrol), will the healer then follow them across the map, too, or retarget?

**Comment by ByBurton** [comment]
> Did anyone already test what happens if the current healing target of a healer dies? Does he retarget immediately, and based on his current position? If not, that makes "volatile" healing targets problematic - e.g. vulnerable patrols troops.

I did. I think he was retargeting immediately. 
And yes, the healer will follow a unit he wants to heal, until he did so.

**Comment by Monsterfisch** [comment]
As I mentioned in the original list healers should be able to switch targets on the fly aka in passing by, that way they don't make ridicules journeys to the end of the world where the units got simply shot down before being reached

**Comment by ByBurton** [comment]
> As I mentioned in the original list healers should be able to switch targets on the fly aka in passing by, that way they don't make ridicules journeys to the end of the world where the units got simply shot down before being reached

I don't think it is too much of a problem. It is a npc, that does not cost you any money to rebuild.
It is fine. Compared to the stupidity of lumberjacks or how the ai treats catapults, this is fine. We should not get too greedy.

**Comment by Heroesflorian** [comment]
@Monsterfisch SH1 had stronger plague, hence more useful apothecaries. Also, outside skirmish mode, scripted plague events give negative popularity (up to -6 or so?), and apothecaries also help removing clouds, thus not just providing a global % damage resistance but also helping to remove the damage sources AND sources of negative popularity (cleared up plague clouds do no longer affect popularity). 

And yes, afaik the resistance is global (for that player), independent of religion blessed % or other things. 

Regarding the size: Well, check out the Abbot or Philipp with their vanilla castles, boasting with half a dozen chapels, several churches and cathedrals. In comparison, 3 healers are almost tiny. And sure, the smallest castles will not have room for them, but neither do they have room for a couple chapels or other large buildings (Marshall has 6 stables!). And considering a big castle doesn't fit everywhere and is more expensive to build, being able to fit another apothecary inside is a nice tradeoff imho. 
Besides, raiding troops do not prioritise religion buildings or healers, so it is (relatively) save to put them outside the walls, possibly even surrounded by some nice gardens for looks, if it is at the back or to the sides of the castle.

**Comment by Monsterfisch** [comment]
> I don't think it is too much of a problem. It is a npc, that does not cost you any money to rebuild.
It is fine. Compared to the stupidity of lumberjacks or how the ai treats catapults, this is fine. We should not get too greedy.

its not about the healer getting killed its about the healer running after a injured unit and not catching up ;) i am proposing that he when a closer unit than the running away one gets in range he switches to that unit instead

**Comment by ByBurton** [comment]
> its not about the healer getting killed its about the healer running after a injured unit and not catching up ;) i am proposing that he when a closer unit than the running away one gets in range he switches to that unit instead

I know what you are proposing, but changing the AI behind will be pretty hard I figure.

**Comment by ByBurton** [comment]
But there won't be a unit closer by @Monsterfisch if he is running directly behind the unit, as it is in a lot of times the case.

**Comment by Monsterfisch** [comment]
> But there won't be a unit closer by @Monsterfisch if he is running directly behind the unit, as it is in a lot of times the case.

That scenario would usually mean the unit he is trying to heal is attacking the enemy resulting in the healer getting shot as well respawn and than start at the keep/the building itself to look for heal targets. It's really just to make sure the healer doesnt follow those units into death on a regular basis, as its painfull to watch a healer trying to catch up with a much faster archer, while there are units to heal much closer by. (It was super apparent in the screenshot I posted as the healer went aaaalll around the castle to heal archers guarding the quarry before healing the engineer standing on the gatehouse)

**Comment by ByBurton** [comment]
> That scenario would usually mean the unit he is trying to heal is attacking the enemy resulting in the healer getting shot as well respawn and than start at the keep/the building itself to look for heal targets. It's really just to make sure the healer doesnt follow those units into death on a regular basis, as its painfull to watch a healer trying to catch up with a much faster archer, while there are units to heal much closer by. (It was super apparent in the screenshot I posted as the healer went aaaalll around the castle to heal archers guarding the quarry before healing the engineer standing on the gatehouse)


Yeah. It is painful. But you see, in the long run, this won't be a problem.

**Comment by Monsterfisch** [comment]
True that. 
I am definitely hyped about this, even more than I was before if that is even possible.

**Comment by Wolfram92** [comment]
I think the new mechanic is a really great addition.

I would suggest increasing the workload of the healers, so that they will stay longer in one place and only heal one person.

I had a match with my badly hurt lord in close proximity to them and they walked up to him, did their little healing motion and then started wandering around aimlessy. So maybe they it's possible to make them concentrate on only one unit at a time and extend their 'healing period'?

Regarding their roaming range, I would suggest having them stay inside the castle, or at least close to their apothecary. It also fit with regards to realism, since usually badly hurt troops cannot be used in the field anymore and have to be brought back to their base/castle for healing and recovery.

**Comment by PitchNeeded** [comment]
On the subject of running units, it will be interesting to see how Wazir's healers try and heal any injured members of his horse archer patrols around the sides of his castle!

**Comment by Heroesflorian** [comment]
And possibly even more hilarious: Nizar's surprise attacks! 
Imagine one of his assassins fights a hostile unit (patrol archer, slave, woodcutter, whatever) on the way and from that point on Nizar's healers will rush out to try and heal up that assassin, giving away the army's position and movement to anyone... :D Poor Nizar!

**Comment by UristMcEngineer** [comment]
If it is possible for the healer to find a new target if his old one dies then it might be possible to find a new target every 10 seconds or so. This would remove the problem of walking past injured soldiers because they would at that point be closer than the original target. Finding new targets should not be used too often though, because pathfinding is probably very CPU-intensive.

**Comment by Krarilotus** [comment]
Seems like this has already been worked into the healers mechanic -> healers cross the whole map now.
I am not sure about stuck units tho, but reopen simply, if you feel like this needs more attention.

**Comment by ByBurton** [comment]
@Krarilotus Healers area of effect / the search radius should be increased imo. Why close this issue if there are still suggestions that can be implemented?

**Comment by Krarilotus** [comment]
> @Krarilotus Healers area of effect / the search radius should be increased imo. Why close this issue if there are still suggestions that can be implemented?

Surrly if the AoE heal would be anything anyone wants still, they can make a new issue for that. Cleaning up older issues while also removing redundant issues will help getting more changes done, rather than leaving them as clutter. Sh0wdown already increased the search radius, as healers roam the whole map already, which is more annoying in my opinion but ok i guess. 
He also stated that aoe doesnt fit for the game, i agree but yeah, if someone wants that anyways, let them make a new issue refering to this one, shouldnt be too difficult.

**Comment by Monsterfisch** [comment]
I agree aoe might be a little much for healing and would, in my opinion, be more suited for a "rework" of the disease system which can be discussed in a new topic. 
As for the pathfinding issues in the op I doubt there will be a lot of fixes for those. on top of all that since the post is fairly old and the healing system had a chance to establish itself atm I personally am fairly satisfied with how it works now =)
