### ISSUE TITLE
Apothecaries and AI castle.

### ISSUE THREAD

**Issue by Lolasik011** [Sh0wdown/UnofficialCrusaderPatch#200]
I think  need to rewrite the AIV castles. Because the apothecaries function has been added. Because not all AI Lords build Apothecaries.

**Comment by Heroesflorian** [comment]
Well, but given abothecaries need space and are expensive, I think not every AI character would necessarily profit much from adding them. Also, they are sort of an "advanced technology" building that doesn't really fit small, simple AI characters like Rat or Snake. 
Also, I'd say there's a lot of other features that the patch adds or changes that probably have more effect on AIVs than the healers, and the healers also may still be changed/adjusted in near future, so I'd say it is too early to adjust all AIVs with respect to healers.

**Comment by Heroesflorian** [comment]
Sure you can edit them... but by what criteria? Before editing them, I think we should first think about what kind of changes would make sense regarding healers. Just adding additional apothecaries somewhere outside the walls feels a bit "quick and dirty", and anything else will require additional modifications in most cases. 

Also, would you include the increased tower siege engine limit as well? What about the other issues that many AIVs have?

**Comment by PitchNeeded** [comment]
I was about to discuss this. Which lords do we think should have apothecaries then?

So at the minute, Emir, Wazir, Abbot and Frederick already have apothecaries in all their vanilla AIVs. Wazir has two in some of his! Sheriff and Nizar have one in some of their AIVs.

Certainly Saladin, Lionheart, Marshall, Phillip and Sultan should have one of them I think. It would go with their personalities, but it might not go with Rat, Pig or Snake's personality as much. 

Wolf and Caliph maybe should have one too, although it wouldn't go so much with their personalities as they are evil lords who wouldn't care about their troops' health too much, but I suppose if Sheriff and Wazir have them then why not Wolf and Caliph as well!

**Comment by PitchNeeded** [comment]
Actually one of Emir's bigger castles no longer has an apothecary with Evrey's fixed vanilla castles, just tested it now. He must have replaced it with the additional houses before the healers became so important with the patch :D.

**Comment by Lolasik011** [comment]
I'll wait for your castles :) @PitchNeeded

**Comment by EchoRevora** [comment]
Not sure if every AI should build apothecaries now.. why not leave it as it is? It makes those few characters that already have apothecaries more special. Lionheart and Saladin are already pretty strong; should they really be stronger? Not every AI uses religion, not every AI produces beer. Why should most of the strong AI's get apothecaries now? Surely it might fit their character, on the other hand it would make a lot of sense and fit character to give the Lionheart crossbowmen instead of archers. But firefly decided not to, and everyone got used to it. Just like they made their decision on which AI builds apothecaries.

I always found it interesting that only 4 characters build apothecaries, now that they're actually more useful I think they should stay the only AI's to use them.

**Comment by ByBurton** [comment]
Wolf should build at least one. He is a tank ai, and even though it does not suit his personality too much, it would give him a large boost to his defense.

**Comment by Monsterfisch** [comment]
I wasn't aware the wolf needed a stronger defense ;) 

Why don't you create your own aiv files to test it out?

**Comment by PitchNeeded** [comment]
Well at the very least I think I think Sultan certainly should have one, it fits with his personality of caring about his troops and Saladin, Phillip and Lionheart are kings who would have almost certainly had the service of healers historically.

> Actually one of Emir's bigger castles no longer has an apothecary with Evrey's fixed vanilla castles, just tested it now. He must have replaced it with the additional houses before the healers became so important with the patch :D.

@Evrey It's Emir2 that no longer has the apothecary in your fixed vanilla castles, it would be good if that was fixed for the next patch! :D

**Comment by PitchNeeded** [comment]
So here's the list of AI lords that I shall add them to in a new version of Everyday vanilla castles that will be ready for the next patch

Wolf (only one though)
Sultan (I really think a healer would go with his personality)
Marshall (he is an advisor in SH1 and so would definitely have some wise ideas such as using a healer).
Phillip, Lionheart, Saladin - they are kings after all so would have almost certainly had the services of a healer historically.

Make sure Emir, Wazir, Abbot, Frederick, Nizar and Sheriff have one in all their AIVs.

Not sure about whether to add one to Caliph's castle but I probably will unless there are any objections here :D . It might not be go with his personality much having one (but the same could be said for Wazir) , but his defensive troops such as Arabian archers and fire throwers are expensive to replace and we all know Caliph doesn't have the best economy so having a healer could really help him.

**Comment by PitchNeeded** [comment]
I don't know where to put the healers in the building order for AIVs though. Would it be OK putting in it last (but before the pitch ditch is created for AIs that use pitch)?

**Comment by Monsterfisch** [comment]
You probably want to have them be built early as some ais have a hard time replenishing defending units so with the healer those units will be kept alive longer.

**Comment by PitchNeeded** [comment]
OK but not so early in bread making AIs, getting their mills and a few bakeries up first is more important!

I will look and see where Firefly have put the healer in the building order too for those vanilla AIVs that have one.

**Comment by Evrey** [comment]
@PitchNeeded Hi there!

- **\@mentions** do not seem to work unless one is already part of a conversation. I just stumbled upon this topic by accident.
- By accident, a few of my Wazirs still have apothecaries. All others are intentionally gone.
- I will not change my mods for new features *(not what I consider to be fixes)* added by this patch for two reasons:
  1. Not every user of my mods also uses this patch, and in that case apothecaries are a waste of space, workers, and money.
  2. This patch tool does not officially support Linux, so I don't support it. Am a Linux gamer.

**Comment by Evrey** [comment]
> I am using your fix

Oh, the fixed vanillas. Totally forgot that they exist.

> and I agree there should be an option to just have your fixed AIVs without additional apothecaries

This patch tool can do what it wants to, have more options or not. I'm just not going to change my master repo, which in turn means that derived work might fall out of sync whenever I update stuff.

**Comment by PitchNeeded** [comment]
> I'll wait for your castles :) @PitchNeeded

@Lolasik011 I have completed Wolf and Sultan's so far. Wolf's vanilla AIs were hard to edit and to find space for an apothecary, some houses and bad things had to be moved. Hopefully I will get another 2 AIs done tomorrow!

**Comment by Heroesflorian** [comment]
He did say *moved*, not ***re**moved*, though.

**Comment by PitchNeeded** [comment]
@ByBurton I understand your concerns but I am a very careful AIV editor (which is why it is taking me a while to do this) :D And I am testing it too to make sure there are no bugs like AI buildings being built and deleted repeatedly in-game.

If I do have to move a few of Wolf's bad things or a house (and I am doing this so only somewhere else to make way for one apothecary, I make sure the things I have moved are put back having the same build stage as originally.

I have only moved houses (some of which are Evrey's added houses anyway as I am working from his AI vailla fix) and good/bad things if I have had to make room for an apothecary, never any other buildings.

**Comment by PitchNeeded** [comment]
I am also responding to different castles: eg. Nizar has only one in most of his castles but for the one with the really long pathway into his castle I gave him two in total because his economy isn't as good in that one and having two healers will allow him to heal more of his troops in that castle that become injured meaning less cost in replacing dead troops for him. :D

**Comment by Lolasik011** [comment]
@PitchNeeded Thanks, I'm waiting :)

**Comment by ByBurton** [comment]
@Lolasik011 my rat ai villages will have healers. And some others as well. Just check in from time to time to my github [repository](https://github.com/ByBurton/StrongholdCrusaderAIV)

**Comment by Lolasik011** [comment]
@ByBurton Thanks :)

**Comment by PitchNeeded** [comment]
Tried to put two apothecaries for Saladin at the back of his vanilla castles, but it turns out that when I tested it they weren't in range of healing injured units on his two front towers, so I will have to relocate them at the sides. Shows the importance of testing AIVs!

> my rat ai villages will have healers. And some others as well. Just check in from time to time to my github repository

Tbh I think out of Rat, Pig and Snake, Snake would actually be most likely to have healers in terms of personality, as he is the most intelligent and clever out of the three. Plus he hires mercenaries so, why not mercenary healers too!

**Comment by ByBurton** [comment]
@PitchNeeded Maybe I will give the snake a healer as well. I wanted to give the rat one, as I think it kind of funny to see him with a healer.
I won't give the pig one, but the Wolf will.

**Comment by Heroesflorian** [comment]
> Shows the importance of testing AIVs!

A sentence to be framed with gold (not only in regard to healers)! :D

**Comment by PitchNeeded** [comment]
> I'll wait for your castles :) @PitchNeeded

My vanilla re-edit with apothecaries is finished, all AIs apart from Snake, Pig and Rat have at least one in my version, I am just testing them today to make sure they are OK and will upload them tomorrow on here for use as an option in the next patch.

**Comment by PitchNeeded** [comment]
@Sh0wdown Here is the link for my Evrey's vanilla AI castles apothecaries edit for the next patch. All lords apart from Rat, Snake and Wolf now have at least 1 apothecary in this new edit.

https://drive.google.com/drive/folders/1gfqCyRqYK9LmV1YgTOeYntDp_N1Q__Dg?usp=sharing

**Comment by Sh0wdown** [comment]
> @Sh0wdown Here is the link for my Evrey's vanilla AI castles apothecaries edit for the next patch. All lords apart from Rat, Snake and Wolf now have at least 1 apothecary in this new edit.
> 
> One other minor change: There are also one or two more small (manned by 1 person) wells on some castles near the new apothecaries, just in case they are targeted by enemy slaves! Sultan's castles now have one small well too and Phillip has two small wells on his castle which had no wells in vanilla.
> 
> https://drive.google.com/drive/folders/1gfqCyRqYK9LmV1YgTOeYntDp_N1Q__Dg?usp=sharing

Included in upcoming 2.10.

**Comment by PitchNeeded** [comment]
> Included in upcoming 2.10.

Thanks :D Looking forward to the new patch!
