### ISSUE TITLE
Color of Ally in "ally menu", if you changed it into something..

### ISSUE THREAD

**Issue by R3dsleeve** [Sh0wdown/UnofficialCrusaderPatch#204]
if you changed your color for example into black, you start a game with like 5 KI's there is a red one as well.
if the red one's is your ally and you open up the ally menu, he is still black (or the color you took.)
see following pic
![01](https://user-images.githubusercontent.com/46421206/50737521-a3c25a00-11ca-11e9-828c-31cbcab3da3d.png)

**Comment by LordHansCapon** [comment]
If the AI sends you any "Video" message, the shield above the video is also the original color. I have looked into it, but it is much harder to solve than one would think.

The problem here is the draw order on the UI. The buttons for the AI icons are drawn earlier than anything else, and they are not simple images but button instances, so fixing it would mean we need to find where these buttons are instantiated. I have gotten as far as fixing the name of the AI in the menu, but got stuck, maybe I'll look into it again.

As for the shield above the "video" message, I haven't tried that one, but I doubt it will be easy.

**Comment by ByBurton** [comment]
@LordHansCapon is this fixed now?

**Comment by LordHansCapon** [comment]
@ByBurton It is fixed, yes.
