### ISSUE TITLE
 Waiting for a new patch ...

### ISSUE THREAD

**Issue by Lolasik011** [Sh0wdown/UnofficialCrusaderPatch#242]
@Sh0wdown  Thank you for not quitting work on a new patch.

**Comment by Lolasik011** [comment]
"The setting to increase the total troop limit was removed because it does not work properly."  I think it could leave optional. 
I liked this function. :(

**Comment by Sh0wdown** [comment]
> I liked this function. :(

Well, but it was simply not working properly. It would just increase the troop limit from ~2360 to 2400 because peasants would stop spawning.

**Comment by J0J0Jo** [comment]
@Lolasik011 Try running extreme, as it is now supported. No problem with the troop limit there :)

**Comment by PitchNeeded** [comment]
Many thanks for the new patch. One note about it:

The description for my edit of Evrey's castles says it has added mangonels and ballistas but in fact that version doesn't have those but **is the one with the added apothecaries and wells**. My thinking was that some people may just want the added apothecaries to the vanilla castles and not the added ballistas and mangonels.

My fault really. I should have been more specific that my new edit of Evrey's vanilla castles didn't have the added ballistas and mangonels. I would like to do a new version for 1.11 which has those AND the apothecaries though, I shall start working on that for the next patch. I would like it to be a separate AIV option though!

**Comment by PitchNeeded** [comment]
Thanks for the new patch.....

It's good that the AI siege melee troops will now all head to kill the AI lord whenever there is a breach, it is certainly a more sensible strategy than some of them going off to destroy buildings first.

I still want to see Emir's raiding Arabian swordsmen attack gatehouses or try and breach the enemy wall if there is no other economic target outside the castle in the next patch. This would mean that Emir's Arabian swordsmen raiders (which are often sent in a big enough force to pose a threat themselves) could kill off weak AI lords or damage their castle economy instead of waiting around outside the enemy castle because there are no other economic targets to destroy. Knights from Marshall, Phillip and Frederick seem to sometimes attack gatehouses/walls/towers if there is no other target but not Emir's Arabian swordsmen raiders strangely....

Speaking of raiders there is still bug where sometimes they stop, often in the middle of enemy territory, and wait for reinforcements instead of moving on to attack other economic targets.
