### ISSUE TITLE
 Arabic and European AI problem with moat.

### ISSUE THREAD

**Issue by Lolasik011** [Sh0wdown/UnofficialCrusaderPatch#259]
Arabic AI does not dig moat, but simply walks around the castle.
I understand that this topic has already been raised. Sorry.
But this is a very unpleasant bug.
![Moat AI BUG](https://user-images.githubusercontent.com/41998977/54315837-4abeda00-45f0-11e9-83ea-8af54db2703c.png)

it would be good if the AI ​​gathered groups of slaves specifically for digging a moat, European AI took spearmen or pikemen and maceman.

**Comment by ByBurton** [comment]
@Lolasik011 Some arabian lords actually do train slaves only specifically for digging up moats.
Sultan for example does not. Emir has a few archers for that.

I believe we already have an issue for this.

**Comment by PitchNeeded** [comment]
> @Lolasik011 Some arabian lords actually do train slaves only specifically for digging up moats.
> Sultan for example does not. Emir has a few archers for that.

Emir's archers advance at the wrong time during his sieges I think, they should advance at the same time as the horse archers instead of waiting to advance with the Arabian swordsmen as they do currently.

Because tower archers prioritize firing at enemy missile units, the horse archers can distract the enemy archers from Emir's advancing moat digging archers (and have more chance of reaching the moat to dig) if Emir's archers and horse archers advanced at the same time.

**Comment by Sh0wdown** [comment]
I think this will be fixable with the upcoming AIC edits.

**Comment by ByBurton** [comment]
@Sh0wdown Even giving them like 100 max slaves as digging units won't really help too much, because their digging behaviour is just so bad...

**Comment by ByBurton** [comment]
Also, looking at the snake for example you would think that he would be awesome at digging moat with all those spearmen.
Well, guess again. He has only 20 spearmen assigned for digging moats, and the rest will just stand around idle if no wall is accessible.
