### ISSUE TITLE
Horse archer  Archers and Crossbowmen attack BUG. 

### ISSUE THREAD

**Issue by Lolasik011** [Sh0wdown/UnofficialCrusaderPatch#260]
I understand that this topic has already been raised.
But this is a very unpleasant bug. Sorry.

I noticed that when Amir goes on the attack, he leaves the horse archers and does not attack 
 by them. It would be better if he killed the shooters on the walls than he waited for the wall to break . 
All AI do the same except The Wazir. The Wazir immediately goes into battle with horse archers to clean the walls of the enemy. 
Crossbowmen with archers also stand aside.

**Comment by ByBurton** [comment]
#104

**Comment by ByBurton** [comment]
I am 100% sure this issue already exists.

**Comment by PitchNeeded** [comment]
The bug you describe seems to be a pathfinding issue, and is often caused by the landscape on some maps I think, if there is an obstacle like rocks or a hill between the siege force gather point and the enemy castle being targeted, some units can get left behind.

**Comment by Lolasik011** [comment]
No. This problem is constantly i encountered, even from the vanilla version of Stronghold Crusader

**Comment by PitchNeeded** [comment]
Well from my experience, I find it happens only on some maps, particularly those with more features on them between the enemy castles like hills, cliffs and rocks that can cause pathfinding issues.

And I [i]have[/i] found it has happened to Wazir too. The only Arabian AI that uses horse archers that it doesn't seem to happen to is Saladin, because he moves his horse archers around during sieges unlike other AIs.

Anyway, I hope it can be fixed eventually.

**Comment by Lolasik011** [comment]
We will hope ....

**Comment by ByBurton** [comment]
The problem WHY they won't attack is, that they are meant to stay behind and act as kind of a backup / fallback unit. To protect the army while it is preparing. They won't move until the enemy keep is accessible
In the AICE (AI Character Editor) you'll be able to give the AI a ranged push unit..

**Comment by Lolasik011** [comment]
> In the AICE (AI Character Editor) you'll be able to give the AI a ranged push unit..

ok.
