### ISSUE TITLE
Emir - efficiant bowmen usage

### ISSUE THREAD

**Issue by Taddl2k** [Sh0wdown/UnofficialCrusaderPatch#274]
The Emir uses european bowmen in his attacks and as defensive troops on his small towers. But the rate in wich these towers are manned is extremely low. So sometimes it takes him like half an hour to get only 1 archer on each tower. 
Is there a way to increase the rate in wich these towers are manned? Because even if there are enough bows in the armoury he still won't recute more bowmen.

**Comment by ByBurton** [comment]
@Taddl2k Stuff like that can be changed by each of you, with the ai character editor.
It will still take some time to finish, but you can adjust each variable that defines an AI lord.

In your case, you would have to adjust the probability of the AI to recruit defensive units, so it is higher.

**Comment by PitchNeeded** [comment]
> The Emir uses european bowmen in his attacks and as defensive troops on his small towers. But the rate in which these towers are manned is extremely low. So sometimes it takes him like half an hour to get only 1 archer on each tower.
> Is there a way to increase the rate in which these towers are manned? Because even if there are enough bows in the armoury he still won't recruit more bowmen.

I used the 'confused' reaction to your post because actually I haven't found this since he has been able to buy in bows (I have found he has been able to man his towers as quickly as any other AI lord and can put 5 archers in each lookout tower) and I have played a lot of AI games with Emir, as he is my favourite AI character in Stronghold Crusader.

I have found in these matches that Emir is quite strong, despite the fact he doesn't have the best defence. Usually he will beat his evil brother Wazir now that he can buy in bows (because of his lookout tower archers being good against horse archers and fire ballistae) and also all those Arabian swordsmen counterattacks and raids he likes to do. The only AI lords that will usually beat him are Saladin (because of all the catapults Saladin creates if he has enough money), Lionheart, Frederick and Wolf. 

But Emir of course could do with some more defensive archers, he has to rely too much at the minute on his Arabian swordsmen sallying forth to defeat enemy sieges on his castle. And of course Wazir and Saladin need more archers on their towers too.

**Comment by Taddl2k** [comment]
Well that's odd because I just reworked all castles of Emir myself and had like 10 to 20 games with the different castles I made and pretty much in all cases he was dragging his feet to even put 1 single european bowman on the towers. (btw my castles are designed after his original ones so that should make no difference) Only after quite some time he put some bowmen on the towers..

**Comment by PitchNeeded** [comment]
> Well that's odd because I just reworked all castles of Emir myself and had like 10 to 20 games with the different castles I made and pretty much in all cases he was dragging his feet to even put 1 single european bowman on the towers. (btw my castles are designed after his original ones so that should make no difference) Only after quite some time he put some bowmen on the towers..

I think with most AIs how fast they put archers on their towers (especially in a low gold start game) depends on whether they face threats to their economic buildings early in the game. If their farms are under attack early in the game, they have to spend gold to create archers to defend them, rather than being able to use that gold to man their towers quicker.

**Comment by ByBurton** [comment]
@PitchNeeded The units you mention, sortie units, are created with the highest priority out of all the units.
Even before defence. Always. And not only if a farm or something is under attack.
But you will notice that especially if those units keep dying, the AI won't be able to restock their defence, or work on an attack force.

**Comment by Sh0wdown** [comment]
This is now adjustable through AIC-Edits.
