### ISSUE TITLE
Question about additional AI tweaks

### ISSUE THREAD

**Issue by ByBurton** [Sh0wdown/UnofficialCrusaderPatch#28]
Just a quick question, @Sh0wdown do you think that it would be possible, to edit the executable in way, that you could edit what kind of stuff an ai uses?
-What economy it builds, and how much of each resource it saves on its stockpile
-Which kind of units are recruited and how many used on a defensive point, on aggressive patrols, on defensive patrols and of course for attacks

Examples:
-Make the Sultan build up to 5 hunters.
-Let the rat build up to 7 apple farms, and add more defensive archers
-Make the Wolf build more iron mines
-Let the pig also recruit archers
-Change Frederick's swordsmen to pikemen
-Let the snake use assassins and very, very, very few arabic swordsmen
-Let the Wolf man his towers with more units, and enable arabic archers
-Let the Sultan recruit up to 5 defensive fire throwers
-Let the rat build supportive shields

**Comment by PitchNeeded** [comment]
It would be great if this was possible; certainly the stronger Arabian AIs in particular (Saladin, Emir, Nizar, Wazir and Caliph), because they have more expensive armies, could definitely do with the ability to produce a few more quarries or iron mines, as they often run out of gold far too quickly. And Phillip definitely could do with at least 1 quarry, at the moment he has none :(

**Comment by Panbutt** [comment]
I agree with trying to add some quality of life changes to the AIs. However for Sultan, you can add 5 hunter huts yourself in the AIV Editor.

Some other things I would suggest:
-Allow Marshal to build more quarries (1 isn't enough for him)
-Allow AIs in general to space out siege engine tents so that they do not block other engineers from entering tents

I like the idea of Snake using assassins. He's described as a sneaky, underhand opponent that prefers letting 'hired help' do his dirty work for him. It makes sense for him to use stronger Arabic units for offense while using weaker European units for castle defense.

**Comment by Sh0wdown** [comment]
Haven't looked into it yet, but I probably will eventually. Philipp & Richard with their puny amounts of archers on the towers could also be added to this list.

**Comment by PitchNeeded** [comment]
> I agree with trying to add some quality of life changes to the AIs. However for Sultan, you can add 5 hunter huts yourself in the AIV Editor.

Yep it would good for AIs to have small economic boosts, another iron mine or two for all the AIs that currently make iron mines is a good option of this as they use less workers than stone quarries and also provide income for iron selling AIs (and for some of the Crusader lord AIs, could reduce costs of buying in weapons), but for AIs that use ale it must be made sure that any additional buildings do not push the population too high for ale buildings to still provide a +8 popularity boost.

> I like the idea of Snake using assassins. He's described as a sneaky, underhand opponent that prefers letting 'hired help' do his dirty work for him. It makes sense for him to use stronger Arabic units for offense while using weaker European units for castle defense.

Yeah I suppose it would go with his personality, although I do like the fact Snake uses laddermen so without the spearmen attacking it would make them useless. 

Other changes that would be good:

More monks in Abbot's raids.
More knights in Phillip's raids. He has enough stables to create at least 20 knights to be sent in a raid.
More pikemen sent in Richard's raids.
A proper siege force for King Phillip. Tunnelers would be a great option for him in sieges as he can create a breach in a castle wall, and once there is a breach in the castle wall, Phillip does often send any raiding knights he may have through to destroy castle buildings such as the granary.

**Comment by ByBurton** [comment]
> More knights in Phillip's raids. He has enough stables to create at least 20 knights to be sent in a raid.
I disagree here. He is a weaker AI opponent, he should not raid as strongly as Marshall. I would prefer him rebuilding his defensive knights around his castle though.
Tunnelers do not sound like King Phillip at all. I would add it to the pig and the snake and / or the rat instead.

**Comment by Flechador** [comment]
> I disagree here. He is a weaker AI opponent, he should not raid as strongly as Marshall. I would prefer him rebuilding his defensive knights around his castle though.
> Tunnelers do not sound like King Phillip at all. I would add it to the pig and the snake and / or the rat instead.

Disagree aswell, i think it would be cool if Phillip does actually use all his stables. But the Knights do not need to be in his raids. Like someone other mentioned, he could use Knight in his attacks.

Everyone has an other opinion for Tunnelers it seems, because i think they would fit for Phillip. The Rat is also an weaker AI opponent why should he use the Tunnelers? I would maximum give the Rat Laddermen, catapults and shields. (Like he used in Stronghold 1)
Ist not an must have but Tunnelers for the Pig sounds good for me.

**Comment by meisanon** [comment]
I never actually see any of the AI using ladder men. Would be a nice addition!

**Comment by Panbutt** [comment]
Considering Phillip's primary use of Spearmen, I think Laddermen are pretty fitting for him. In his SHC description it says his "over-reliance on Knights as his main fighting force is most often if not his undoing". It makes sense to me that he would overly use Knights in his forces, whether be for defense, patrol, attacks and harassment.

**Comment by PitchNeeded** [comment]
> Tunnelers it seems because I think they would fit for Phillip. The advice is therefore weaker AI opponent why should he use the tunnelers?

But with spearmen as the only units that can get onto an enemy keep, he will still be weak! I think tunnelers would be a better option than laddermen because Phillip's best strategy I can see for besieging a castle is managing to create a gap in the walls so he can send any raiding knights he has through to destroy the granary and castle buildings before his enemy can repair the gap in the walls!

>  Like someone else mentioned, he could use Knight in his attacks.

I mentioned it. 😃  It would certainly look amazing if Phillip gathered a group of knights, archers and spearmen (and one or two catapults) to attack an enemy! Yes it might not be the most effective way to use knights but it would fit the SHC description of Philip's 'reckless insistence of the use of knights as his main fighting force'.

**Comment by Flechador** [comment]
> Considering Phillip's primary use of Spearmen, I think Laddermen are pretty fitting for him. In his SHC description it says his "over-reliance on Knights as his main fighting force is most often if not his undoing". It makes sense to me that he would overly use Knights in his forces, whether be for defense, patrol, attacks and harassment.

> I mentioned it. 😃 It would certainly look amazing if Phillip gathered a group of knights, archers and spearmen (and one or two catapults) to attack an enemy!

That sounds all good for me. The King of France definitely needs more Strength! He kinda feels so bugged for me as an AI Lord. Because he has so many weird things going on. (Not using quarries, dont man his Tower properly, mostly using only one Stable but Building so many, attacking only with spearmen,..)

**Comment by ByBurton** [comment]
> That sounds all good for me. The King of France definitely needs more Strength! He kind of feels so bugged for me as an AI Lord. Because he has so many weird things going on. (Not using quarries, don't man his Tower properly, mostly using only one Stable but Building so many, attacking only with spearmen,..)

Attacking with spearmen sounds fine to me. I like that. I just feel like he should have support of siege engineers. Preferably battering rams.
He should use a few more knights, but neither for attacking nor to destroy enemy economy. I would prefer him to have defensive knights.
He would be too strong and too much like the Marshal...

**Comment by PitchNeeded** [comment]
Yep battering rams would be excellent for Phillip, about 3 or 4 in a siege and that would make his sieges unique for an AI. The rams could open up that all important gap in the castle defence so that his raiding knights could get in and cause havoc. He would benefit though from bringing some archers in his siege forces to try and protect the engineers from enemy arrow fire so they could make the rams.

> Attacking with spearmen sounds fine to me.

Well now with the improvements in AI attack number increases over time in this Unofficial Patch, he seems to finally be able to send big numbers of spearmen eventually from what I have seen and also spearmen have been made a little more resistant to arrows in the Patch.

**Comment by Lolasik011** [comment]
Philip's one problem is his castle.

**Comment by Lolasik011** [comment]
By the way, it would be great if the wolf used knight.

**Comment by brooklynzsmac** [comment]
Richard should use knights, as they are seen amongst his starting troops during "less gold, more troops" mode.

**Comment by PitchNeeded** [comment]
> Richard should use knights, as they are seen amongst his starting troops during "less gold, more troops" mode.

Yes great point, I think he should recruit a few, but to make him different to Phillip and Marshall, he should just use them for defensive purposes, not raiding (and use bigger numbers of pikemen than he does currently for raiding).

**Comment by Rakso69** [comment]
I think that additionally to the patch there should be added a mini-mod to-mark option allowing one of the AI lords to do it's absolute best to the maximum of modding possibilities(being capable of doing all troops and using multiplayer-like gameplay economic behavior, additionably if possible: act like a smart online human-player).
Myself I've had such a thing in mind 2 years ago. That's when I've made a Wolf AIV manage to do a prospering 250 population economy consist of 54 workshops, 10 breweries, 10 Inns and both cathedrals. All this stuff mixed alltogether had allowed him to gain tons of gold quicky by running whole game on between -22 to -24 tax, selling also the over-produced weaponry and apple baskets - gathering a whole ton of these even on such a high population, by tricking their income and consuption through accurate regular purchase of cheese and bread.

PS: A wolf capable of doing bread would be even better and more fitting for most maps. Sadly his behavior doesn't allow him to build wheat farms. Even if I place these for him directly in the map editor he declines using the wheat, taking rid of by selling it immediatly as quickest it gets dropped on the stockpile, causing bakers doing nothing whole game.

At any case, he was capable or earning more gold than current top online players! when I was testing him play against them. Definately -24 tax whole game on 250 pop is more efficent than -24 tax on 460+ pop for a while period of time.

READ THIS:
I know how alot of players don't enjoy the hardcore-like stuff and multiplayer pro way of gameplay, but I think that modding shouldn't be limited only for singleplayer-fans. I don't insist on buff a "regular or Evrey's mod" Wolf to the maximum, but (I repeat), as a mini-mod to-mark on the installer option for the part of the community, which simply is being too good for singleplayer AI-fighting, as a great additional challenge to exercise on.
I'm aware that a challenge might aswell be achived by playing AI 1vs7, but having a strongest possible AI in a 1vs1 environment, that could work for itself on a better way than the 7 allied alltogether definately looks better and less messy.

Think about that, how great would it be to modify an AI to play better than even the greatest multiplayer legends to walk across this game from over a decade back, like: {{DHK}} HolyLord, Gx_S0ck3tz`, @rm@, XXoDDu$$, FireDragon, Bartholo, Luis7, Blacky... and way more... These do not play anymore, but remained in memory as icons of multiplayer passion and addiction to develop all possible aspects of gameplays.

Slowly more and more players are playing with each next year. Even if they do so, they're taught already differently, than they would be past on Gamespy Arcade, in the community of the upper mentioned.

Knowledge about the game is also dying. On 2007 probably 99% of possible in-game bugs were discovered. Now probably 1/3 of these got fogotten.

Creating a challenging AI opponent playing at the peek level of any of the old top players would surely bring interest to the game, and the mod. Similar situation as in Chess with Kasparov vs Deep Blue AI, where AI first time whooped a legend's butt :)

**Comment by Lolasik011** [comment]
0_0 Wonderful idea !!! 
P.S 
If not difficult, please throw me your wolf AIV.

**Comment by Rakso69** [comment]
@Lolasik011 I won't share him, as now as I have just seen this Unofficial Patch going on, I'll be up to come back over my 2 years old work to provide him multiple variations of this one castle to be fitting on more maps. For now You can see my 2 years old Wolf over here dealing with the Rat on the only 400x400 map in the game I was working over him. His eco & stats. The biggest flaw of my Wolf AIV for the current moment is exacly that he isn't flexible to being capable of playing efficently on other maps.
So I'm going to emphasis my AIV editing over making him multiple-map compactible, by making more versions of his AIV files(Curretly he has still one) on my free time. Especially fit for the multiplayer maps such as EventMap07 or Aw-lub. Cheers.
![wolf1](https://user-images.githubusercontent.com/45049934/48720391-e54d7480-ec1f-11e8-8b13-2f1532e4907f.jpg)
![wolf2](https://user-images.githubusercontent.com/45049934/48720406-eb435580-ec1f-11e8-81d8-88610e9695bf.jpg)

**Comment by Lolasik011** [comment]
Rakso69 Strange ... As you like.

**Comment by ByBurton** [comment]
One of the newer issues #215 also mentions this stuff.

**Comment by Sh0wdown** [comment]
Closing this, as it is now possible with AIC edits.
