### ISSUE TITLE
Slaves: balance suggestion?

### ISSUE THREAD

**Issue by ByBurton** [Sh0wdown/UnofficialCrusaderPatch#285]
Slaves are underpowered. Almost every arabian lord is relying on them. Especially for filling up enemy moat / digging own moat. But they are basically worthless. 
I would suggest decreasing the cost even more, to 4 Gold maybe (which is a lot, if you sum it up).

**Comment by Lolasik011** [comment]
@ByBurton i agree

**Comment by Truetobi91** [comment]
Moat is not only problematic for most arabian AIs but all in all for most AIs in the entiry game. Basically everything that doesn't use tons of Spears/Macemen/Pikes won't really be able to dig up moat if there is at least a decent number of archers on the enemy keep. And even Spears and Macemen will have problems as long as the opponent has a viable defense. 

That's pretty much one of the reasons why I started to create my own aiv and I'm really carefull with placing lots of moat. 

You can do that of course but I really don't think that will change much. Maybe Kalif will have a benefit from ti because he's constantly spamming them. As long as he has like 200 gold he will instantly train new slaves after the previous ones have been killed.

**Comment by ByBurton** [comment]
@Truetobi91 WRONG!
It is even worse. Even those AI lords who USE units have the ability to dig, don't use all of them to dig.
They have a special variable for that.
E.g.: Snake uses a lot of spearmen for attacks. But only a max. of 20 spearmen to fill up the enemy moat.
E.g.: Wolf uses a lot of pikemen for attacks. Do you ever see more than 8 filling up moat?

I fixed that in my balance file, by increasing the max. amount of units to dig enemy moat for almost every AI lord (only exception being the Sultan).

**Comment by pwnasunt** [comment]
I think a slave should have high enough health to withstand one shot, but not two to increase their longevity. This should involve proportional gold cost increase, of course.

I found that any AI can afford slaves rather easily. What makes slaves not last long is that they are being vulnerable to projectiles. Increasing their defenses will enable them to e.g. fill in one more square of moat before falling.

**Comment by ByBurton** [comment]
@pwnasunt Nope. Health is fine. They are meant to be one shot, srsly. Slaves would be scary. Really scary.
And you will see fire everywhere....

**Comment by pwnasunt** [comment]
@ByBurton You are right, but in contrast, they would also be less accessible by the gold increase. I don't advocate that the AI won't be able to hire them at a lower rate, but we would still see less slave raids in the long run. 

Reflecting on your original suggestion, I do not think that 1 gold less would make slaves any more accessible than now. The AI can comfortably fund them, the problem is that their survivability is abysmal in the presence of even a few archers. Also, attack waves including slaves would not form up any faster, because the AI will still have to produce the more costly troops (Arabian archers/swordsmen/etc.).

The AI also seems more liberal at building patrols with the UCP, I think they should not have much trouble intercepting slaves, on top of their usual ranged sortie groups.

**Comment by ByBurton** [comment]
But they SHOULD be one shot by archers. They have no armor at all, not even clothes dude.

**Comment by Panaminion** [comment]
Is it possible to increase the running speed of slaves?  In contrast to buffing their armor, this might fit them more, and in a large wave more of them might make it to the moat for digging, thus increasing their effictiveness?

**Comment by ByBurton** [comment]
Maybe, but that's the same issue as increasing hp.
I would suggest either increasing the dig speed or lowering the cost.

**Comment by ByBurton** [comment]
@Monsterfisch But you will see much more burned down buildings as well.
Fire is already overpowered as heck.

**Comment by pwnasunt** [comment]
Mitigating ember spark frequency or burning damage could turn down the slave damage on humans. By experience, regular fires have a separate damage type from pitch ditches, so it might be possible to tune along with the slaves.

**Comment by Panaminion** [comment]
i kinda like fire :D, but yeah that could be a problem. Moat digging speed itself however does not fix the problem that slaves mostly do not reach the moat... maybe it is possible to lower the speed at which houses catch fire, when a slave attacks it (as compensation)?

**Comment by Monsterfisch** [comment]
if slaves rech buildings faster just make it so that the buidlings catch fire later meaning they have to swing their torches 1-2 times more often to set it ablaze

**Comment by Truetobi91** [comment]
> 
> 
> if slaves rech buildings faster just make it so that the buidlings catch fire later meaning they have to swing their torches 1-2 times more often to set it ablaze

In terms of fire power what sounds neutral **can** be a net loss of power. If we changed it so slaves set buildings on fire after the same total time but spend less time running and more time hitting that also means they spend more time not moving -> more time being easier to hit. Just considering

**Comment by Monsterfisch** [comment]
you give some and you take some ;).
The consideration of having them be less effective when setting buildings on fire would only be necessary if the speed up would prove to be too much of a power-up for the unit after all. maybe it wouldn't even be necessary in the end the idea is to make slaves more effective to dig up moats which generally speaken in my opinion is a much more important role for the slaves than harassment units as they are for many chars the only way to fill in those moats. and as soon as a char or player has a semi-decent defense the current slaves don't even stand much of a chance to set stuff on fire in the first place i would argue.

**Comment by ByBurton** [comment]
Closing this, slaves are okay as they are I guess.
