### ISSUE TITLE
Nizar aic/aiv problems

### ISSUE THREAD

**Issue by Truetobi91** [Sh0wdown/UnofficialCrusaderPatch#290]
Currently engaging with building aiv for Nizar and already running into problems I haven't encountered with most other AI yet but that could possible reappear with the few I haven't done yet. What is most problematic about most of these problems is that they are super inconsistent. I tested several different versions of my first concept and put them into mirror matches against each other which has worked out well for all other AI until now. Nizar however does many things on one side that he doesn't do on the other (see bold). 

- Nizar only stocks a max of 40 stone which means if you build the trading post before any stone structures he will sell 10 units of his starting stone (standard game setting). -> Low Prioirity

- **Nizar is building his stone quarry extremely late for some reason. Even though he doesn't even have that many stone buildings he takes ages to complete them. -> Medium Priority**

- **Nizar builds a pitch rig rather early on. This should be lowered in priority in favour of the stone quarry. -> Medium Priority**

- **Nizar has problems building his mills even if you use the aiv pause feature. He even tends to flood his stockpile with grain, stopping his wood income and eventually putting himself out of action. -> High Priority**

- **Nizar rather buys flour instead of wood to build mills which is gold inefficient and doesn't solve any of his production errors (see above) but rather exacerbates them. -> High Priority**

- Slaves are not digging his moat properly and often stop the work after a few tiles before they are ordered to continue again even though his moat with only few building steps. -> Low Priority

If you have ideas how to improve his behavior from AIV side I'd be pleasee to hear them, otherwise it'd be great to look into these systematic changes from AIC side in the future. # #

**Comment by ByBurton** [comment]
Yes, the maximum amount of stone he keeps is 40 (+ a random amount of up to 4), so max. 44 stones.
He builds his quarry after he reached a population of 20.
Pitch rig is fine imo.
What do you want to change about the wood problem? Make him keep more wood? That would make him require probably a 4th stockpile. Make him keep less wheat, hops and beer? Would make him less durable if he is under siege.
He does not buy flour INSTEAD of wood. That is a general AI problem. If an AI notices, one its workshops, bakeries, breweries, mills, inns can not work, because a resource is missing, the AI buys it with the highest priority, after food.
I did not notice the slave digging problem. But that may be a general AI problem as well. The AI can not dig for all its worth.

Most of the problems you mentioned can easily be edited with the AICE.
And well for your aiv... make sure his first mill is the very first building step, and then stockpiles, and then the market and then the granary. After that mercenary post. Then the first bakeries. Then breweries, the next bakeries. Then the first inn, then towers and gates. Engineers guild. Moat. More inns. Last bakeries and breweries. (I did not mention walls, because fuck Nazir having walls)

**Comment by Truetobi91** [comment]
Building a Mill as very first is indeed a good idea, going to try that definately. And that he builds the quarry upon reaching a pop of 20 is very valuable information, thanks for that. 

In regards of the wood: I think all of the bread making AI have the problem with their mills, not only at the beginning of the game but also once they have to rebuild themselves after a heavy siege that hurt destroyed their mills (or e.g. when burning down entirely or when not disabling economy sell for emergency recruitment). On top of that, AI often also just builds 2x 10-wood-buildings instead of a mill upon reaching 20 wood DESPITE the mill being higher in priority from their AIV. 

Therefore I'd like to at least test a change that let's the AI build mills from gold similar to how phillip buys his stone buildings from gold (as far as I observed that the stone buying process is skipped there, but not sure about that). Best case would be that the AI checks their wood AND gold when trying to build a mill. 

Do you think that's possible?

**Comment by PitchNeeded** [comment]
> He does not buy flour INSTEAD of wood. That is a general AI problem. If an AI notices, one its workshops, bakeries, breweries, mills, inns can not work, because a resource is missing, the AI buys it with the highest priority, after food.

As I said on a recent issue, all the AI's do seem to have a problem buying wood to replace economic buildings late game.

**Comment by PitchNeeded** [comment]
Another thing, Nizar3 needs fixed I think!

![nizar3](https://user-images.githubusercontent.com/44881289/55185708-d5750c80-518c-11e9-9207-59ec896b54c9.jpg)

So he still has that big path for enemies to follow but not such a big path for his workers to get out. His economy is almost always awful in this castle.

I think the best solution is that he would have to have a small gatehouse and drawbridge at the front of the island near where the water pot is. The water pot and a few statues would have to be moved!
