### ISSUE TITLE
Priests giving fighting boost for troops/ workers

### ISSUE THREAD

**Issue by Halbarad1** [Sh0wdown/UnofficialCrusaderPatch#300]
Hey, 
I really do like the new healing system and I thought about priests too. Some people were making suggestions that it should be easier to get more popularity but I don't really like that, because churches and priests are really effective in a desert place with low population. But I also don't like that the one priest in a single cathedral/ church/ chapel doesn't have an effect on a bigger population. My suggestion:

- blessed workers/ soldiers are getting stronger as long as the blessing is active (and counts in the players popularity). This could for example also negotiate the negativ effect of pillory, gallows, ... that effects the players troops.

**Comment by Lolasik011** [comment]
I think that monks should not give buffs to the troops. Because only the Abbot currently uses the Monks. This means that only buffs will be distributed to it. When AICE is released, then perhaps more AIs will be used by the Monks, although I very much doubt this .....

**Comment by DarkThief-Darek** [comment]
@Lolasik011 I think Halbarad1 meant the priests from the chapels, churches and cathedrals, who wander around and blessing people for a popularity boost. Not the military unit recruited in the cathedral.

But I also don't like the idea of a troop bonus. Because you can't distinguished if a troop is buffed or not, the effect wouldn't last long and would only benefit the defender.


I recently noticed that in the last stronghold 1 mission, where you siege the wolf, the wolf has 3 priests in his one cathedral.
Maybe that's a way to buff the religion, if the church has 2 priests and the cathedral has 3 priest workers. I mean, it's a pretty big building and costly.

**Comment by PitchNeeded** [comment]
I think workers could be buffed a bit by religion but not troops (we already have positive fear factor for that).

**Comment by Rakso69** [comment]
I totally dislike this idea. Let's keep the game as it is imho. But if someone likes then ok. Personally I'll never mark that one on installation if so.

**Comment by Sh0wdown** [comment]
A temporary effect would be really hard to implement. So I think I will skip this.
