### ISSUE TITLE
 AI script Tournaments !!!

### ISSUE THREAD

**Issue by Lolasik011** [Sh0wdown/UnofficialCrusaderPatch#336]
I propose to arrange AI Tournaments :dagger: 

Put your AI scripts here and we'll see who is the best.:dagger: 

Can create a leaderboard and celebrate the winners and the best AIs there. But we need a person who will shoot this on Youtube so that people can see the results.:dagger: 

You can create rules and restrictions on construction for AI. And then it will be interesting to watch. Suggest your ideas ...:dagger: 

I really think tournaments will be held on this site . https://challonge.com I have not figured out how to use the site :D

Can of course create a table in Excel....

P.S If you want this of course...:dagger:

**Comment by ByBurton** [comment]
It is easy to make an invincible AI, just because their siege behaviour is bad, and you can make AIVs that are basically invincible.
As much as I love AI tournaments in different games, I really dislike the idea of one in Crusader.
AI tournaments really only work if you can also change the behaviour.

**Comment by Lolasik011** [comment]
> It is easy to make an invincible AI, just because their siege behaviour is bad, and you can make AIVs that are basically invincible.
> As much as I love AI tournaments in different games, I really dislike the idea of one in Crusader.
> AI tournaments really only work if you can also change the behaviour.

:( ok Close

**Comment by ByBurton** [comment]
Sorry..
