### ISSUE TITLE
AI economy running out of wood

### ISSUE THREAD

**Issue by FurorGermanicus** [Sh0wdown/UnofficialCrusaderPatch#348]
Fletchers and poleturners are the backbone of castle economy. When the AI is producing or bying enough wood, selling the produced weapons is most important for gaining money.

However, when the AI is bankrupt it doesn't buy rawmaterials anymore, the economy runs out of wood (especially when woodcutters don't get through) and those important worshops are standng still, resulting in economic chokehold.
Only with sufficient money, the AI is buying rawmaterials and the economy flourishes.

-) One solution could be to define a minimum ammount of wood, perhaps there is an unknown parameter "MinimumWood"? This parameter should be set very low, so that the wood can only be used to produce weapons and not for buildings. 

-) Another solution could be to establish an economic money reserve for the AI, so that troops are only recruited above that threshold. I havent found a possibility for that with the yet known AIC Parameters. Perhaps increasing the threshold for switching from weak to strong state?

The AI could also save a strategic money reserve for the case of longer sieges, to quickly restore troops and castle buildings.

Any ideas on how to implement this?

**Comment by Truetobi91** [comment]
I totally agree on that!

An AI's running wood production is not only core to several AI like Rat and Snake, but it's also self-sufficient - actually super profitable. Even buying wood to run wood production is profitable so AIs should always buy wood for their production to run. 

I found my Rat buying wood in stacks of 5 but I couldm't say if that was from attempts of rebuilding woodcutters (+2 from patch) or if it was in the attempt to buy it for the production. 

Sadly, I don't recognize any parameters that have values to think of it being a "minimum wood" or "buy wood for production" even though I admite that'd be the easiest and most likely most efficient way to do such a change.

**Comment by Russianstory** [comment]
I recently suggested something different here. True, this can also be implemented in parallel with your ideas. It is necessary to make the tree give not 12 boards, but for example 24 boards. And so that one board would give 4 bows or 2 crossbows or 4 spears or 3 pikes. Well, the same will be both more convenient and more productive for both the AI and the players.
--
Я как то недавно тут предлагал несколько другое. Правда, это тоже можно реализовать параллельно с вашими идеями. Надо сделать, чтоб дерево давало не 12 досок а например 24 доски. И чтоб одна доска давала 4 лука или 2 арбалета или 4 копья или 3 пики.  Ну это же бдет и удобнее и продуктивнее как для ИИ так и для игроков.

**Comment by Heroesflorian** [comment]
Similar issues occur for other resources as well, e.g. wheat and flour for bread production: When low on gold, the AI often doesn't manage to keep a (profitable*) bread production going (without regular wheat income from farms), as any profits from selling bread and taxes are used to recruit troops until the AI is too broke to buy new wheat to continue production. 

Only when the AI has an economy strong/large enough to actually not only sustain itself but generate more gold than the AI is able to spend on troops, it will manage to keep it going. 

(*e.g. in combination with -5 fear factor for +50% bread output per flour, and +8 beer coverage)

**Comment by PitchNeeded** [comment]
I know I have mentioend this before, but there is also the problem of the AI sometimes not buying in wood to replace destroyed farms, quarries and mines. I think that happens if the AI still has one or more woodcutters huts (so doesn't buy in wood to replace buildings as it senses that there is potential for wood to be gathered instead). The problem is that, especially late game, the wood is often in a contested position and the woodcutters keep getting killed.

**Comment by Krarilotus** [comment]
check #159, so reopen if necessary, but i think its redundant cuz of dublication
