### ISSUE TITLE
Balancing Update: Shields.

### ISSUE THREAD

**Issue by GRhin** [Sh0wdown/UnofficialCrusaderPatch#367]
This is mostly a response to finally playing online multiplayer, the games end up with everyone using the same strategy in all circumstances, I see this as unbalanced. There are two units I would like to see changed slightly to fix this.
**This thread is about Shields.** From my research in online forums about this, players agree that they need to be balanced, however when they say "No Shields" the second unit (Horse Archers) become more of a problem ( will address that in another thread)
Personally I think these are OP, they allow players to basically kill off a lesser force with little to no losses. **Therefore I think they should have a health reduction**, so that a tower filled with crossbows actually have a chance to destroy them before being killed off.
Im not sure the exact reduction required for them still to be usefull, but not OP, some testing there would be needed.

**Comment by Heroesflorian** [comment]
One can use shields on towers as well, by the way, to balance out "offensively used shields" ;) But yeah, shields can feel quite OP either way. 
Besides possibly tweaking their damage resistance for projectiles, one could also consider making them more expensive and/or adjusting their movement speed - which currently far exceeds that of engineers that do not carry a heavy shield, which doesn't make sense. 
I think the "shields + horse archers" combination would become a lot less easy and flexible to play with, when shields move slower - either you have to split the shields and archers, becoming vulnerable, or you have to sacrifice speed and mobility for protection. 

Having said that, though... there already are some counter strategies available, including... 
- mangonels to decimate shields and ranged troops alike before they can even shoot, 
- catapults to one-hit-kill shields and ranged troops alike before they can even shoot, 
- for defense, preparing some well-placed pitch ditches for a hot surprise, 
- launching diseased cows using catapults or trebuchets to deal area damage, ignoring/bypassing the presence of shields altogether
- catching your enemy by surprise (or outmaneuvering him) and slaughtering shields and ranged troops with melee troops - typically assassins (fast and stealthy) and/or knights (fast and tanky) - in combination with own shields or ranged troops to absorb or distract projectiles. 

This means, even though portable shields are quite powerful for sure, rebalancing them needs to be done with care, imho - especially regarding multiplayer.

**Comment by GRhin** [comment]
Long post warning, didnt mean to go on for this long, but its just how I am, dont take it personally (some people do for some reason)
I agree these strats mitigate their power, however;
- mangonels are quickly lost, esp if the enemy use their shields to protect attacking catapults.
- Catapults take time to launch both rocks and cows, in the case of HA and shields often they have moved by the time the projectiles land, so its hard to use effectively. If they are using cats+shields to take out your towers, you usually have to move your cats beyond your walls to hit them, and you expose yourself to the same problem, so you have to use pre-placed trebuchets, which are very inaccurate.
-Pitch ditches are one time use, then you have to wait for the enemy to be long gone before you can replace it. They can easily pull back (taking nasty casualties, but depending on when you lit the pitch they may be out quickly, or will have inflicted nasty casualties back), wait out the fire, and return again.
-That leaves outmaneuvering, assasins are good, but often they take more casualties than they inflict when up against HA, and they arent much cheaper. knights are better, but also more expensive (156 gold if buying weapons, 40 without, and the space for stables isnt always easy to get, plus 400 gold per stables), and again they take huge losses if the HA charge straight into them instead of running away to let the shields die.

Now I am not saying that it cant be done, it can. However, as it stands, defending your walls is impractical as the ways to break through the shields all involve leaving your walls. In that sense the walls hinder your response (as you have only certain locations to get out of them).
Reducing their strength against archers wont make any of the strategies you suggested any more effective; mangonels might take out shields faster, but cats are still one-shotting, pitch is doing the same thing, diseased cows do the same thing, and hitting with melee will have no noticeable increase in speed destroying the sheilds.
As the best response is to attack with assassins or knights, maybe macemen (i havent tested their speed against a shield, so they maybe too slow to catch them) it locks the game down into 1 strategy progression for all maps, for all situations, there is no point in building swords, spears, pikes or monks,, the range issue means fire throwers and slingers are also out, slaves can be caught by HA which abound. This isnt a fault of the defensive units, its a fault of there being one offensive strategy that outperforms every other strategy in every way. And thats the problem Im wanting to get fixed, make it so there is enough of a trade-off of going for HA+shields that other tactics become a bit more reasonable. 
I want there to be a situation where spears or pikes is a smart move (aside from just digging the moat), or where using ladders or seige towers to get units onto the walls instead of destroying the walls could be a great strategy. Heck even rams there are no point in using, but thats another issue entirely.

Now for some numbers to illustrate why i think the shields can safely be reduced drastically.
Shields shields take 160 regular arrows to destroy, which is more than any other unit except european swordsman which take 200, HA take 8. most attacks involve no less than 50 shields, which would take 8000 arrows, so its the equivalent of forcing your enemy to kill 40 european swordsmen before they are allowed to kill off your archers which are killing them off at the same time. OK, so its slightly different because as you kill shields you can hit the units they were protecting, but its a pretty close analogy. And there is no other strategy that can match that. 

Effectively turning  HA into Swordsmen that can shoot (their defense against arrows is even higher than Knights), is definitely OP, maybe turn them into Pikemen (50 arrows) or Catapults (65 arrows) would be much better, you dont have to reduce them that far, but they shouldnt be even close to Knights (135 arrows) in my opinion.

**Comment by Halbarad1** [comment]
- slow down shields to speed of normal engineer (or less)
- increase costs to 50 gold
- don't let them climb walls


That should be minimum change. I personally think they would be still extremely useful and since we can spam siege equipment much easier with the patch I think now is the time to reduce the shield spam a bit.
And still people don't have to worry about balance issues because you don't have to use it. 
But here's the thing: If we start right now with the biggest balance issues in Stronghold, maybe we can take the game that far in Multiplayer that people actually do use strategies which do seem logical and it would make much more fun playing Stronghold Crusader online.

**Comment by Rakso69** [comment]
@GRhin Stop asking people playing multiplayer on 1.41 version what should be balanced out, because they got no clue about the gaming on multiplayer at all. Most 1.41 players are singleplayer fanboys whom never really experienced much of multiplayer. I think you should ask about balancing out the game players from 1.1 version. I suggest asking for sure X-CON clan players or either W.L clan players or KoRT for balance suggestions regards the game. Let profesionals speak and just discuss the matter with them. People on 1.41 use to play 20 mins no rush with towers allowed, but catapults banned dude... lol
You guys always complain about things being broken, but those are actually used on pro games and not considered being game breaking. Hmmm

**Comment by GRhin** [comment]
Frankly Rakso, that was a pretty pointless post.
If these "Pros" only play 1.1, then this patch is irrelevant to them, also they arent going to be using this patch, they wont even use the official patches (why is that btw?). Furthermore, I didnt say "only 1.41 players can respond" so im not asking them only, im asking anyone who uses this patch, regardless of version.
You see, basically you say "others are happy with the balance" with no reason for it except "the ones agreeing are clueless". Thats not an arguement. You are entitled to your opinion, as am I. If you want to discuss our different opinions I am happy to do so, but to invalidate the opinion of everyone who disagrees with you simply because of what version of game they use, is not a discussion. It is prejudiced, I guess youd call it "versionist".
I am the "singleplayer fanboy who never really experienced much of multiplayer", simply because i never knew how to get on multiplayer, I have 1.41 cos i have the game on steam (lost original discs from back in the day). However, that does not mean I dont know what I am talking about. These "pro players" are welcome to enjoy a game that has one strategy worth pursuing, and effectively playing the same game every match (ive been watching them on youtube, there is very little difference between matches, id be happy if you could point me at a match that is very different if it exists, i just havent been able to find one). But thats not the game I want to play. I want to play a game where things can surprise me, where I build units to counter what I think they are sending, then they hit me with a different set of units so i have to scramble to change troops to counter that instead.
Go to AoE2 multiplayer games, and you will see what I mean. AoE has the advantage of having different civilizations with different units/bonus's etc, but even in games where everyone uses the same civilization each player can use a different unit combination, and still have a chance to win. You dont get that in SHC, and these two units I believe are the reason for that. If you disagree, thats fine. If you think the game is perfect how it is, then dont use the patch,but if you are going to join the discussion, at least contribute to it, rather than just telling everyone that their opinion doesnt matter.

**Comment by Rakso69** [comment]
Actually your post is the most pointless ever that I saw.
First of all, the UCP works for all SHC versions, no matter if it's 1.1 or 1.41.
Pro not playing the patch right now, doesn't mean they wouldn't if the patch received a balance update, but that one shouldn't be spoken in the first place by multiplayer newcommers, but actually have sense, and changes should be spoken by someone experienced with how multiplayer works, so actually others can discuss with the Pro guy.

You can't say you're experienced, because you watched a few videos on youtube. lmao man, that's pathetic. Listen up to yourself. Thy simpleness shall carry over upon your unsophisticated ego.

Pros play on 1.1 because it's way less laggy in games with more players than the newest version, also the camera movement is sightly way faster than the one from HD versions(that's slow af, even on "fastest"). Not to mention that, they had toking about actually patching the game to 1.41, but guess what? The .map files have somewhat changed(Firefly...) and you can't send oldschool maps to others unless you figure out how to do that, but why one should if the game is still laggy, and camera is still slow?

No matter what Crusader 1.1 is also Crusader, as well as 1.41 is. I didn't said that you guys trashtalk, I just said that it might be wiser to ask actually the skilled players about their opinion how to balance, as they know further more strategies, maps and rules, so you can argue and discuss the matter with anyone who can speak experienced in the first place.

Sure, up to 13(I think you said something like 4, right? LMAO) types of units are used on multiplayer, but I doubt you're expecting anyone to start using spearmen on multiplayer, right? About counter it just depends if you're watching pro-for-fun, or actuall pro players. Listen, I'm not a SHC player, but I'm a SH1 pro. These two games online ain't that much different anyway. In a real game, when you're playing you watch what your opponent is doing and play against him, same way in Crusader:
If enemy makes cats, you make more cats,
If he starts making HA, you make shields,
If he starts making assassins, you make HA, etc.
You obviously always have got time to counter your opponent, because he needs to cross the map to reach you. So, if you play against someone equal or better, you always use that advantage to buy time. It takes time to cross the map, right? so in THEORY, you will always have more by the time the enemy crosses the map to reach your castle. The enemy can never reach your castle with more gold value at your own castle, than you can create if you play properly. I don't mean to camp. You can't be stuck in your castle, you have to control the map, but you can control the map defensively. A game won by rushing and pushing isn't that much of a real competetive game. If one dies to a rush he's simply garbage. Same way if you keep attacking someone, and he can't defend from that he's just garbage. The attacker is always on the disadvantage. A real game is won by gold and time, kind of economy war, also cats obviously. cats are the game winner in a true game without rules.
You wouldn't understand that without playing multiplayer, or get taught about it. Videos ain't good, you miss all the very little details when you watch them.

I don't care about AoE2. That's trash example. This game has nations, and over a 100 of unit types for sure(it's obvious most are going to be used, if in most cases only thing that differs them are the names). SHC hasn't.

See me? I just speak with my experience. You must base your arguing with either videos(that aren't yours, not sure even who you were watching lol) or either by making example of other games. If you like AoE2 go ahead and play it. That's not Stronghold bruh.
Here are some channels worth most check:
https://www.youtube.com/channel/UCb6T-0wFwL6Qbzgd-WNYcVQ/videos
https://www.youtube.com/channel/UCgwuz0nYCUPRzTJszQN35sg/videos
https://www.youtube.com/user/TheCrusadefs/videos
https://www.youtube.com/channel/UCiUOU9IrHgPo3terxetuW5w/videos

**Comment by Rakso69** [comment]
@GRhin Notice that I didn't said you all can't argue. I said that you shouldn't be the ones, to type the suggestions in the first place, but to argue about ones written by someone actually experienced. You're the one who discriminates the players, because of the different version they're playing on, so rethink that. Cheers.

**Comment by Lolasik011** [comment]
Do not quarrel, friends. The balance can be done in Launcher. And he will be chosen by someone who likes to play with such balance.

**Comment by Rakso69** [comment]
Yeah sure. Let's add some my little ponny to the patch. If someone doesn't like to have little ponny in their patch he can just disable them in the options, yeahhhh... Come on.
Why not just do things right and properly already on first attept, instead of adding crap options, and then later on forget about the whole topic, because a nerf was already added to the options in the patch installer, so why bother, right? No matter that it was totally amateur designed.
Just do things right guys, otherwise the quality of the further patches is going to be low, and noones gonna play with it anyways, so why even bother. Discuss balance with players who play online. Singleplayer players duscussing about how to balance multiplayer is just funny, like are you all gonna ever play online anyways? lol

**Comment by GRhin** [comment]
OK Rakso, That was a little better, Ill check over your videos today. but maybe you can name me the 13 units used online are? I have given you the 6 that I have seen (Shields, Catapults, HA, Knights, Assassins, and some random trash unit just to dig moats). Im not saying im experienced based on the youtube videos, I am saying that I havent seen anything else, and I have tried to do what research I can.
I do have one major issue though. "I'm not a SHC player, but I'm a SH1 pro"
The balance updates are using shields (available in SH1) and HA (which are not), you cant say you have experienced input while admitting you dont play with the issue at hand.
The issue here is that you are asking me to go somewhere else to ask about patch-related suggestions. The better option, if you think someone else can have a better input, is to suggest to them to come in and join the discussion.
I respect that you have pointed out counters to the 3 main units people attack with, though it has been mentioned by these players who's opinions you have dismissed already, however you havent actually said what you think about this issue, and thats why i say your posts are relatively pointless.
At first I assumed you didnt want the balance update (thats fine, you dont have to use them), but now im thinking you want them, but just dont want anyone using the patch to discuss how to do it. 
I have never claimed im experienced, or an expert, or anything along those lines. What I do understand, however, is unit balance, its how i think and work and play. That does not mean I am right, but it also doesnt mean that I am not allowed input. 
This ticket is not here to limit who can make suggestions or have input, quite the opposite, the players you want me to talk to dont have a convenient forum or chat room in which i can ask, and as this suggestion is patch related, why shouldnt I be posting it somewhere the developers of the patch can watch and understand the views of their users. If they choose to ignore the suggestion, sobeit, but if i ask elsewhere, then put in one post here saying "pros agree with me" its actually less likely to get their attention. That is why I ask you to get players who you think can give "experienced input" to come here and give it. I dont know why you think its my job to go find players who have nothing to do with this project to tell me what I should suggest to the project.

**Comment by Rakso69** [comment]
@Grhin I'll reply further tomorrow. Troops only for now:

1. Horse Archers(usually limit 50 for player on nffs(that's how pro do balance for now lol), but allowed unlimited on nof games),

2. Portable shields,

3. Assassins

4. Knights(rarely on nof - better safe gold for catapults, way more used on nffs),

5. Pikemen(enemy moat diggers only on nof games, but pretty much used in every possible game on nffs, all the time as the tank unit that takes the damage of enemy unit first and "meat shield" cover your knights or asassins).

6. Arabian swordsmen(mostly nffs. Used as assassins replacement in combo together with pikemen army),

7. Catapults(nof games only obviously),

8. Battering ram(usually combined with rush strategies),

9. Slaves(dig moat),

10. Monks(used in nffs as economy defence from assassins sneaking - they have a really fast charge on agressive stance(spearmen too, spearmen are similar used in SH1 on defence, but vs archers/knights sneak eco cuz no assassins in SH1). On nof monks used as meat shield cover for catapults "mass"(mass means 15-60 catapults in one place, main fire range force) against stone throwed from enemy cats - monks take the stone hits or in defence of the cats mass vs flag assassins attacks(N + 4 rally point fast assassins trick), called in nof slang "asachi trap"),

11. Laddermen( afp - army for pop. You gather ladders to disband them and then tax -24, you do that if enemy plays really agressive and harass woodcutters. So if making woodcutters makes no sense you do laddermen, or on low peace time settings, like 5pt, where small eco),

12. Macemen(situational, mainly played on no market games, sometimes in noffs games, but isn't that much considered a multi-situational effective unit on either of strongholds, it sure can harass enemy on small 2vs2 pretty much easy digging moat, cuz of their walking speed and numerosity).

13. Crossbowmen(used in no market + alot on regular, but on very long games, mainly for map control purpose from towers in your castle and cover for outside catapults "mass" like a bonus support unit for monks, also very good vs 1 pixel compressed units, but afaik before that wasn't, but I think now it's considered being "gay strat" lol).

lol bonus, maybe instead of upper crossbowmen:
14. Trebuchets(used in nof games obviously. They're situational now I'd say, cuz people don't use the on defence that much now cuz I think that started being considered gay strategy. lol
Imo trebuchets behind mountains are gay-strat, but whatever).

**Comment by GRhin** [comment]
Thanks for that Rakso.
Ill go ahead and ignore the "Laddermen" entry, because you say they arent used as units, only as a eco boost. Correct me if Im wrong.
As fir Arabian Swordsmen being a assasin replacement, how does this work? they are slower, and can be seen from a mile away, so they cant fullfill any of the purpose that I am seeing assassins being used for.
Macemen and Crossbowmen seem to be rarely used by your description, crossbowmen being in towers is an interesting point seeing as every video in the channels you linked did not use towers.

Anyways, im not here to argue units tbh, i brought it up as an illustration of strategy. It seems from your post saying "that's how pro do balance for now lol" that you agree, and the pros agree, that a balance update is needed. How about instead of argueing over who is allowed to have input on that balance, we argue over how that balance should be implemented. That is what this ticket is about after all. If you can get these pros discussing and suggesting balance updates, I can just make suggestions and bring up potential issues, and let their "experience"  shine.
The reason that a pro player isnt neccasarliy the best person to work on balance updates is that they are used to working with the current balance, while new players can adapt easier and so test new balances more fairly, they can think outside of the box because they dont know what isnt supposed to work, they dont know you shouldnt do something, so they do it (or suggest it here), and it may show the balance to be good or bad depending on how it works.
I am not saying pros shouldnt have input, they definitely should, because they have seen all the scenarios in with the current balance falls down, Im just saying that it should be a collaborative effort from multiple skill levels.

**Comment by Rakso69** [comment]
@GRhin
https://youtu.be/wv4WQAdbzq8
Example or arabian swordsmen game from Sergiu's Nightmare guy(that's his YT channel), he also uses plenty monks.

Note that you just catch the point only where it proves your words. I said HA limit is used only on nffs games, the ones where cats are unallowed, because of that exact reason, also cuz assassins and pikemen would easly die from arrows from many HA. The rules developed as years have passed. Players used to play 20pt high resource maps before pros switched to 10pt low resources. It was due to newcommers - easier to handle less things.

On other side in nof games HA are unlimited and used to destroy catapults, and take off assassins, but also use to die super easy. Furthermore you don't always do use shields on your HA in nof games. Sometimes you just leave them behind, like when dealing with catapults, because it's always better option to lose 20 HA from cats, than lose 20 shields due to tue fact, that remaking shields again wastes more time, but also watching the enemy as much as possible, which is crucial in catapults games.

HA limit on nffs is not actually only HA limit, but all shooter units limit, that's why you won't see tower xbows on nffs games - players use the limit on HA only, cuz they're fast units that can fly away from a fast enemy.

You can see tower xbows being used on long nof games, as I said, like this one:
https://youtu.be/78XJFVOfE_A
That's Defs channel. Looks like you didn't actually seen his videos at all, because he uses plenty of pikemen in his games, yet you thought and said on top of the topic, that they're not used at all, and later on that my videos proof my point.

Sure. I let my SHC pro friends know about this topic and type-suggest changes here. 

Myself I'm just describing how things look like on multiplayer at SHC, I'm not suggesting balance changes on my own, because I'm not an SHC pro player(althrough I'm perfectly aware how the games works, due to my own experience and self deduction, so I wouldn't even know what to balance properly, so, as you can see - I'm simply not discussing about it.

I'm a Stronghold 1 pro player, and myself I tryed a few times, but I just can't... Crusader too boring for me due to being way less dynamic than Stronghold 1, so I hadn't exercised to be a good player there, neither do I have time, either passion for it.
That's my youtube channel tho. You can check my vids if you don't mind.
https://youtu.be/hyJcWcT3Fqc
On Stronghold 1 all units are used online, I'm just not fan of macemen tho, so you won't see them yet on my vids, but they're good aswell, especially vs pikemen. SH1 is sightly way more about eco counter-play your opponent, than through units.

Maybe same on crusader, but only on the "true" games, where two totally evenly matched Crusader pros meet on a fight, but you hardly find such games around anymore, because players skill-level dropped sightly, since the legendary players left the game somewhere around 2012 - 2013. You can see no game is played defensively and carefully as I described, neither economy is further more developed after peace time ends, and neither game uses to reach the so called "army limit" anymore, that's a shame, because the army limit games are actually only the beginning of the very skillful games. ;)

Cheers.

**Comment by GRhin** [comment]
Ok, thanks for the input Rakso. The reason I reacted to your messages is because I am trying to make suggestions to create a game that is more enjoyable, and basically,how i understand your response, you told me, to shut up, and wait for someone with more experience to try and do that. You didnt actually contribute to the discussion, as I understand your posts, but have told those that have contributed that they should just shut up and wait for a pro, who doesnt use the mod, to make balancing suggestions (though they may use the patch **after** a balance is made)
If I have misunderstood where you are coming from, I apologise. 
This thread is meant to open a discussion, and I am more than happy for pros to join in and help us improve SHC. However if they are unwilling to do so, Im not going to just wait for someone you consider pro to have mercy on us, I am going to do my best.
If we get a balance update, I would happily test it rediculously (assuming I can find opponents willing to test with me) and fine-tune it. If one of the developers can give me instructions on how to easily make these changes myself, I can then assure you that it wont get forgotten untill the balance is fixed.

I promise, I didnt fixate on the part of your post that proved my point and ignored the rest. There is nowhere I have found that explains what nffs or nof means so if there were other parts of those rules that invalidate my response i apologise, however from your words, these "rule-sets" are set as a poor-mans attempt to fix the balance. If I am incorrect, feel free to educate me. 

It sounds from your last paragraph that you think the best players have left, but with them playing the game feels much more balanced? If this is the case, can you suggest why these best players left? Sometimes they just get bored and move on, but I wonder if the unbalanced strategies (such as the ma spam) they felt invalidated their skill. I could be wrong, and probably am, as I know nothing of the online community of that era, but if the reason is anything game related then it may illustrate a balance issue that we should be looking at instead of shields if you think shields are fine as-is

**Comment by Rakso69** [comment]
@GRhin Np.

nffs - no fire & no flying stones(fire being fire, flying stones meaning cows and stone from either catapults and trebuchets being shoot on someone's army. Actually catapults and trebs are totally banned on nffs games. Usually 50 HA(shooters of all kinds actually) limit.),

nof - no fire only(It's pretty much like stronghold Crusader on no rules, only fire being banned, mostly due to humans being just too smart using it. The games are mainly played with catapults & trebuchets and throw stone on troops & cows. No limit HA),

Sometimes players add rules such as kok off(king on keep off), meaning you're supposed to surround your king(Lord) with either stone walls and moat, as he can be sneak killed anytime by opponent whenever he wants, but usually pro players play without sneak killing lords - army first, then lord, so you pretty much don't need to worry about him in the game, and he can stay on top of his keep 24/7,

also players sometimes add Noafp rule(No army for pop), meaning players are unallowed to make laddermen, but need to restore their population through turning back to work their put to sleep buildings.

The best players left the game due to becoming serious adults and community starting to behavior much, and much worse with time, moreover there was noone strong enough to challenge them, they simply were too good for anyone, that's all. Althrough the multiplayer history of both Stronghold 1 and Crusader is a really beatiful and interesting thing to listen about, but afaik that's an offtop from the matter so I won't get toking about it further, as it would have took hours. I can leave some easter eggs about it for anyone if he'd be interested to check it out tho:
http://bestofcrusader.weebly.com/the-greatest-of-all-time.html
http://bestofcrusader.weebly.com/
![history of SHC](https://user-images.githubusercontent.com/45049934/57615287-a4ee0400-757b-11e9-949b-00f422065ad3.png)
I don't know if shields are fine as they are, neither horse archers. lol I don't really care. I'm just trying to do something good and advice wisely. Someone else like [X-CON] Maly would know how to balance the game for sure, and could give a hint or two, or as much as possible regards everything. I'll try to ask anyone very good to comment over here, really!
I have just chosen this topic randomly, you know... lol I could aswell write those comments and all of our conversation could either be on your second topic regards Horse Archers. Doesn't really matter. That was rather a general hint from me, you know. Didn't care on which topic I wrote it. lol

Cheers.

**Comment by Rakso69** [comment]
@GRhin You can as well, just post a topic on this forum, now that I'm thinking about it.
http://bestofcrusader.weebly.com/
There are plenty of oldschool and new SHC multiplayer pro players there. Someone sure will notice. ;)
Just advertise them about your topics over here.

**Comment by GRhin** [comment]
So i just watched the video you linked that used towers, and noticed that they werent using sheilds at all. I assume that that is another rule set. If so, then it seems to be evidence of reducing the effectiveness of shields increasing the importance of castle building, in that removing shields making building a tower worthwhile in the minds of these pros. Or at least in the mind of Scofield who had built them. Am I incorrect in this analysis of the situation?

**Comment by Rakso69** [comment]
@GRhin There are shields in this game. Shields just ain't that good when there are so many catapults and mangonels in a game. Think. lol That would be just a waste of gold.

**Comment by PitchNeeded** [comment]
Shields do need a speed reduction I think, it isn't realistic at the moment.

Shields are undoubtedly overpowered both in multiplayer and in single player so perhaps there should be a cost increase to build them I think.

Also maybe increase the damage fire ballistae and burning arrows do to portable shields a bit, considering portable shields are made of wood and would catch fire easily.

**Comment by DarkThief-Darek** [comment]
> Also maybe increase the damage fire ballistae and burning arrows do to portable shields a bit, considering portable shields are made of wood and would catch fire easily.

I don't think that's a great idea. Fire ballistae do enough damage already and burning arrows shouldn't have any advantages, because it's free to get them.

**Comment by GRhin** [comment]
its free to get burning, but you are limited to how you can get them, that change would mean that the shields whould operate the same untill they are in range of walls, as often they are protecting catapults which will destroy any wall with a brazier in no time. for that reason archers on walls with braziers are pretty uncommon in multiplayer from what I have seen (Rakso can correct that if he wants to) so that change alone would likely not change how the shields perform all that much.
Admittedly I have not played multiplayer with strong walls so that may change this view somewhat, im not sure.

**Comment by Heroesflorian** [comment]
Afaik, the strong walls option for multiplayer makes troops unable to attack walls, but doesn't affect siege engine damage inflicted to walls. 
Which may sound nice at first ("soldiers destroying walls is unrealistic!"), until you realize that is essentially just buffing catapults and such, making games more about catapult spam and less about using "regular" troops... at the same time, AI opponents cannot really handle that restriction, making their attacks even more useless than normally. 
And in fact, catapults wouldn't be used to destroy castle walls in reality, as it would take forever to do so, as catapults don't hit hard enough - thus, SH-style catapults were actually more used against troops in reality^^ To destroy walls or towers, you'd need large trebuchets which hit A LOT harder than any catapult could, and even then their damage against proper stone fortifications was magnitudes smaller than what it is in the game...

Anyway, one thing I'd like to point out: "Pro players" usually play "no fire and limited total amount of any ranged troops" or "no fire and no flying stones" most of the time, but with shields and horse archers. Thus, what is considered OP by pro players are mostly two things: 
- **Fire** (fire ballistae, pitch ditches, general fire mechanics), and 
- **Catapults** (as well as trebuchets) throwing rocks and cows 

Thus, buffing catapults or fire ballistae generally doesn't sound like a good idea to me... 

Moreover, without catapults, trebuchets, cows and fire, ranged troops in general are too strong compared to melee troops, making a general cap of ranged units necessary in games without fire and flying stones to avoid eternal stalemates where the defenders on walls/towers simply kill anything that approaches with ease. Thus, buffing fire ballistae, braziers/fire arrows, and generally ranged defense doesn't sound like a good idea either. 

Also, braziers cannot be utilized by the AI that well, they add visual and rendering clutter to the game, are free and can result in graphical glitches especially with AIs. Plus, braziers are free thus shouldn't give direct buffs - "free buffs" is unbalanced already - and also should not be treated as a flame thrower. 
Fire arrows in the medieval era were a mostly stupid idea, reducing damage against troops, reducing range and rate of fire, increasing cost, and doing almost nothing against buildings either. 
If you had a thousand fire arrows vs an unprotected area with straw/thatch-topped hovels, then you might be lucky to get a handful out of the thousand fire arrows to maybe get some smoldering started, but then again that would most likely be put out immediately before it becomes more than smoldering, even without water buckets just by stomping it out or similar means. Also, if you have unprotected flamable buildings, any sensible person would - assuming you want to actually start a fire - just get themselves some torches and then use those to light fires (which does work, and is cheaper because torches are way easier, faster and less expensive to make than arrows, which in reality also are not available in unlimited quantities unlike Stronghold). 
Hollywood-style fire arrows simply are complete and utter bullshit. 
In order for fire arrows to actually be somewhat effective, you would need to rely on extremely flamable material that will immediately light on fire from a spark or a bit of heated metal already - in other words... something like the Stronghold pitch ditches (which in themselves would be too expensive, too not-invisible, etc to be widely usable in reality, though). So... braziers / fire arrows are really not good for dealing significantly more damage. If anything, you'd realistically add a 0.2% chance to light no fire a siege engine, in exchange for a -10% damage output in general. Not particularly sexy, right? 

Things that are more realistic: Throwing oil pots with trebuchets (no, not those huge Hollywood fireballs!), as well as shooting "poison arrows/bolts" (= poke a regular arrow/bolt into a pile of feces, dirt, carcasses or similar, then shoot). 

Also, when balancing we have to consider different scenarios: AI vs AI, Human vs AI and Human vs Human. 

Obviously, right now for Human vs AI no unit balancing whatsoever can change that human players will have to restrict themselves when playing against the AI, in order to have a challenging game. 
Either by not playing effectively (e.g. not using many siege engines, not building up huge economies, not using shields, horse archers, crossbowmen, assassins, moats, fire throwers, etc...) or by playing alone vs many AIs with gold advantage. 

Thus, balancing changes for singleplayer / casual multiplayer with human players and AI players are quite difficult imho (with a few exceptions)... essentially "anything except spearmen", more or less, will appear OP when used properly against the (stupid) AI. 
Really underpowered units for singleplayers would be... laddermen (already got buffed), spearmen (already got buffed), Arabian swordsmen (already got buffed). 
And yes, ranged troops, particularly crossbowmen (defensively) and horse archers (mobility / offense) both tend to be a bit OP when they reach a critical mass to annihilate approaching infantry or smaller amounts of hostile ranged troops. Shields buff ranged troops, making those more OP in combination when the opponent doesn't know how to deal with them. 
The AI generally doesn't know how to deal with that, neither how to attack effectively, prioritize economy vs military, adjust to map geometry, use any sort of "rock paper scissor" counter-unit strategy, deal with fire, place farms or other resource buildings intelligently, ... 

Making shields slower would be realistic (given non-shield engineer walking speed and basic principles of physics), would make "horse archer + shields" a less effective combo, and - relatively at least - make "crossbowmen + shields" a more effective combo as a consequence. 
This would also make shields, relatively speaking, more effective on defense atop towers - which is not the original intended usage according to Firefly, but more importantly also slightly favours defense which already is problematic nowadays unless you add "lots of catapults / trebuchets" to the game, which the AI currently is not capable of, sadly. Also, the AI currently cannot use shields atop towers. 
Making shields more expensive would... make them more expensive, obviously. This would have little effect in situations where you have plenty of spare gold, but make them a less effective choice when you are low on gold. 
Making shields more vulnerable in general would make them less viable, but also less "fit for purpose" as a consequence; making them more vulnerable to specific units like fire ballistae or fire arrows would allow players to more specifically adjust to opponents using shields. 
BUT... human players already have a number of ways to counter shields... on the other hand, such new specific weaknesses/counters would again leave the AI behind as it cannot adjust to this.
