### ISSUE TITLE
AIVs Demolish everything after a period of time 

### ISSUE THREAD

**Issue by Admiral-Gumpert** [Sh0wdown/UnofficialCrusaderPatch#383]
My game yesterday started to act weirdly , Some of the AIVs just builds his castle normally and he would also attack and raid the enemys , but after a period of time the AIV will demolish everything even he will disband his on tower units , and some of the AIVs will not demolish the buildings and will only disband units and some will do both things and some will stop workers only ,

I actually tried many many times to fix this bug , any suggestions?

**Comment by GRhin** [comment]
was it certain maps or all maps?
sounds a little like the they decided they were running out of gold and demolised buildings to sell for gold. This can happen when their castle design blocks them from reaching their resource and/or farmland (or locks them from the rest of the map, which is pretty much the same thing).
if its all maps, try uninstalling the mod to see if the issue is there (if this fixes it be sure to let the patch developers know what settings you were using) if that doesnt work, maybe try the sledgehammer approach, fully uninstall (ensuring the files are all deleted from your computer) and reinstall.

**Comment by Admiral-Gumpert** [comment]
Its was on the AIV's purpose , and it doesnt appear when his gold is not enough or a blocked bulding he keeps building it after demolishing it over and over , but he would demolish everything even farms and quarries and iron mines for no reason all at once , and his popularity drops utterly fast to 30 and down , and i dont think it was caused by the map neither the AIV

**Comment by Halbarad1** [comment]
Can happen with AI like wolf that uses many recources but not so many storage. If the storage is nearly full but the AI has no wood and the market gets destroyed the AI starts to destroy wooden buildings to get some wood (like bakerys, ...). It doesn't get any back because its storage is full and it can't sell anything because it has no marked. In time, it also destroys towers, ... to sell the stones it gets by destroying the towers to buy some wood. Doesn't work either of course. 
Solution 1: More storage for AI 
Solution 2: Activate mode where marked doesn't cost any resources from the patch.

**Comment by GRhin** [comment]
Another possibility that I noticed using tathas castles (i believe) the castle design placed the market in a certain place, but the neighbouring ai built there first so no market was ever built despite having enough wood for it. Then more or less what Halbarad1 described happened with no way to fix it. Maybe try a different AIV setting in the installer?

**Comment by Admiral-Gumpert** [comment]
Maybe the solution could be returning the market cost to 5 woods, and then every AIV should have enough stockpiles as you said, I really didn't think of that
