### ISSUE TITLE
Saladin and Emir's wells are no longer switched off whenever there isn't a fire

### ISSUE THREAD

**Issue by PitchNeeded** [Sh0wdown/UnofficialCrusaderPatch#385]
I noticed that Saladin and Emir's wells no longer switch off whenever there isn't a fire, like they did before. 

Not sure if that is a good thing, which it will allow them to respond quicker to fires, it can lead to population shortages and less recruitment (especially together with the ale farm spam issue that has been mentioned before). Of course another house could be built in their AIVs but increasing the population may impact adversely on ale supply and fear factor.

It would good to have the option to adjust whether wells are kept on or off whenever there is no fire for an AI.

**Comment by Truetobi91** [comment]
My AIV are all balanced around wells being constantly manned. I'd love to know how to do that permanently for all AI because it's super frustrating to plan you AIV around a proper fire defense just to see it burn to the ground because they didn't even man them until they are completely set ablaze.

**Comment by Admiral-Gumpert** [comment]
I just want to know how did you manage to make them  do this "Switching off unused peasants"

**Comment by PitchNeeded** [comment]
> I just want to know how did you manage to make them do this "Switching off unused peasants"

It is on 'no switched off buildings mode' (which I use to stop that annoying bug that sometimes happens where AI bakeries switch off while they are still in the process of making bread) but this switching off buildings mode was not supposed to include wells (it didn't at the start whenever I first used it).

**Comment by Heroesflorian** [comment]
_Any_ AI will have their **wells switched on by default** (even in vanilla, no patch involved) whenever they have a bit of gold reserves (above ~500 gold or sth like that). 
Whenever they have their wells switched off, that usually means they are simply out of gold (or just have everything set to sleep due to being in fear during attacks or similar), which causes them to go into some sort of "saving mode" - the AI then also is less likely (or even 0% likely^^) to restock any wood, flour, wheat, etc in the stockpile, causing even more economic disruptions as a consequence, as production comes to a grinding halt. 
Anyway, wells set to sleep is a sign of constant gold shortage, nothing else. 

Any AIV that has insufficient housing is just badly designed; wells/waterpots are a regular part of castle population. And besides the (weak) "it just is like that, deal with it" argument, there's also proper arguments for that behaviour: 
1. If wells are manned when a fire starts, the well workers can react a lot quicker, extinguishing a fire while it is still small, before _everything_ burns. 
2. Especially due to worker loss often preceding or going hand in hand with fires, and AI trying to recruit nonetheless, manning before-sleeping wells when the fire is already burning does often not work out well, making things a lot worse. 
3. Furthermore, always-on wells allow the AI to aid allied AIs with firefighting. 
4. More population - if properly planned for - doesn't really affect the AI... more taxes, more gold, more awesome!

> It is on 'no switched off buildings mode' (which I use to stop that annoying bug that sometimes happens where AI bakeries switch off while they are still in the process of making bread) but this switching off buildings mode was not supposed to include wells (it didn't at the start whenever I first used it).

The patcher setting to disable "switching off buildings" is supposed to apply to resource processing buildings that are **always** set to sleep by the AI when running out of the corresponding input resources (no matter whether bakeries or weapon workshops) and having 0 units of those resource types stockpiled for a fixed (short) amount of time. 
Fear-based or (for wells) gold-based setting to sleep of buildings is an entirely different behaviour independent of that patcher setting. 

> My AIV are all balanced around wells being constantly manned. I'd love to know how to do that permanently for all AI because it's super frustrating to plan you AIV around a proper fire defense just to see it burn to the ground because they didn't even man them until they are completely set ablaze.

@Truetobi91 Possibly a better economy will allow your AIs to always (or at least usually) have a bit of spare gold which makes them have their wells manned permanently. Of course, under some circumstances, e.g. when constant recruiting of expensive sortie troops at high rate (popularity 100) and immediately sending them into their deaths nonstop, it can be nearly impossible to create an AI-economy strong enough to be fully "immune" to gold shortage in all cases. 
Also, a proper fire defense does **not** rely on wells being manned all the time. Manned wells certainly help and are desirable whenever feasible, but a proper fire defense uses more than "you just have to place enough wells" to work. The amount of wells (as long as there's a few wells at all) is usually less important than 2 other factors: 
- Campfire not burning: This allows the AI to get new peasants that can be turned into well-workers, lowers losses of workers and soldiers, and generally benefits any burning AI unless there's 200 hostile troops trying to storm the keep right now... How to achieve this: Avoid having flamable material near (in a radius of ideally 7, but at least 4-5 tiles to be effective) your campfire! Non-flamable material includes things like moat, walls, towers, gates, stockpiles, dungeons, gardens, statues, shrines, wells, water pots, empty space, killing pits, stairs (including stair5 tiles which are accessible from the ground and can be used to create functional streets if one wants to)... generally speaking, if fire from the outside cannot spread onto the campfire, you are almost golden! 
- Not everything else burning: This allows the AI to use their well-workers to extinguish a fire while a good chunk of their castle economy is still up and running, and especially to fight a fire that has a limited area. Larger fires are generally more dangerous/negative/whatever than small ones, obviously, but smaller fires are also considerably easier to extinguish even with relatively few well workers. 
How to achieve this:

**Comment by ByBurton** [comment]
Close this pls?

**Comment by Krarilotus** [comment]
we have now a fire nerf option. If further improvemetns are needed, open a new issue
