### ISSUE TITLE
Restore unused scribe audio files.

### ISSUE THREAD

**Issue by MikillRosen** [Sh0wdown/UnofficialCrusaderPatch#397]
What I mean is Make the game use the unused scribe audio files, such as Granary_Attack.wav, Granary_Destroyed.wav, and Lord_Killed_01.wav.

**Comment by Halbarad1** [comment]
Do you think the game would benefit from including these sounds? Because a message like "A Lord has been killed" is useless when you hear their death-scream and get their death-message. 
Also an extra message for the granary being attacked doesn't seem necessary to me. 
I don't think that it would annoy me but I don't think including it would improve the game either.

**Comment by Sh0wdown** [comment]
This issue does already exist, please continue discussing this idea here: https://github.com/Sh0wdown/UnofficialCrusaderPatch/issues/122
