### ISSUE TITLE
more maximum population for overall map

### ISSUE THREAD

**Issue by Krarilotus** [Sh0wdown/UnofficialCrusaderPatch#405]
Hey there,
as i was testing AI fights, i saw quite often, that the maximum population on the map was reached, and no more new peasents spawned. I am not sure how high the maximum map population is, but it must be around 2,5k units (peasants included)
I woud recommend increasing that, since it makes the ai battles way more fun.
In Crusader Extreme it shoud be already unlocked, but i can not find, how to increase the maximum population for the whole map in Crusader.

Best Regards,
Krarilotus

**Comment by Halbarad1** [comment]
He (Showd0wn) didn't find it as well, there was a time with such an option in the patch when he thought he found the solution to the problem, but it didn't really worked out, so you now got the option to delete your spells in Crusader Extreme. Since you can also copy all maps from Crusader to Crusader Extreme (and delete your Crusader Extreme maps) you can play Crusader Extreme as if it was normal Crusader (except missions, but they don't normaly play a role in overpopulation/ AI battles)

**Comment by Krarilotus** [comment]
Ah ok, thank you, yeah, that fixes the problem....

**Comment by Sh0wdown** [comment]
Issue already exists in https://github.com/Sh0wdown/UnofficialCrusaderPatch/issues/81. Gonna this one.
