### ISSUE TITLE
Nebel des Krieges

### ISSUE THREAD

**Issue by bySintexPL** [Sh0wdown/UnofficialCrusaderPatch#406]
Ich würde mich freuen wenn es einen Kriegsnebel in dem Spiel geben würde

-> dies ist bezogen auf den Multiplayer

Bitte :D

**Comment by ByBurton** [comment]
Würde ich nicht auf Multiplayer beschränken.

**Comment by Heroesflorian** [comment]
Ich denke nicht, dass das auf absehbare Zeit kommen wird... es ist verdammt schwierig, so ein großes Feature ohne Sourcecode aus dem Hut zu zaubern und ins Spiel zu integrieren. 

> Würde ich nicht auf Multiplayer beschränken.

Wenn die KI auch darauf angepasst werden soll, wird das nochmal aufwändiger. 

Natürlich, cool wärs schon, wenn es sowas gäbe^^

**Comment by GRhin** [comment]
Are you sure regarding the AI? As far as I know the ai sends it's attacks based on global data, e.g location, score, gold levels etc. Rather than based on what you have, they also seem to send the army to the same location regardless, I don't think you need the AI to respond to fog of war, as they kind of behave like its already there I think.

Sind Sie bezüglich der KI sicher? Soweit ich weiß, sendet das AI seine Angriffe auf der Grundlage globaler Daten, z. B. Standort, Punktzahl, Gold-Level usw. Anstatt auf der Grundlage dessen, was Sie haben, scheinen sie die Armee auch an denselben Standort zu schicken, glaube ich nicht Sie brauchen die KI, um auf Nebel des Krieges zu reagieren, da sie sich so verhalten, als ob sie schon da wäre, denke ich.

**Comment by Sh0wdown** [comment]
Denke dass das zu schwierig umzusetzen ist.

**Comment by gunthermann** [comment]
Actually it might be possible cause i had the idea today that one might be able to copy the invisibility of assasins to every unit and if possible to every building / wall just with double / Xtimes the detection range so that assasins still have their role as assains  

But then theres still the problem that assasins when spotted are seen by everyone not just by the one who spotted them and their allies

Es ist vielleicht möglich wenn man die Unsichtbarkeit der Meuchelmörder auf alle Einheiten und Gebäude sowie Wälle kopiert im bestenfall nur halt mit doppelter / X mal Entdeckungsreichweite damit die Meuchler nicht ihre rolle im spiel verlieren.

Jedoch währe dann noch das problem das  Meuchelmörder wenn sie entdeckt werden von allen gesehen werden nicht nur von dem der sie entdeckt hatt und seinen verbündeten

The first picture shows me seeing them the second shows me being in a enemy team and the third shows that both the ai and i can shoot at Assasins that he spotted 
![Assasins3](https://user-images.githubusercontent.com/44819955/107140923-ba958680-6925-11eb-8dbe-9aab11418837.gif)
