### ISSUE TITLE
English AICs

### ISSUE THREAD

**Issue by GRhin** [Sh0wdown/UnofficialCrusaderPatch#438]
Hi Guys, 
Just checking out the new version, and noticed that some of the new AICs dont have english translations. Specifically Tatha and Xander10alpha's version. Id love if someone could translate for us mono-lingual schmucks.

**Comment by Monsterfisch** [comment]
@showdown this might be a neat tool going forward when it comes to translations. I talked with a couple of people whose native tongue is supported here and they are all amazed how accurate it translates.

**Comment by Sh0wdown** [comment]
I don't handle the content of the .aics, but you could contact the creators themselves.

From Tatha's YouTube channel:
E-Mail:     Tatha-YT@gmx.de 
Discord:  https://discord.gg/AYvxsrK

Not sure how to contact Xander, maybe mentioning the profile here works. https://github.com/Xander10alpha
Otherwise he was active in this thread: https://github.com/Sh0wdown/UnofficialCrusaderPatch/issues/419

**Comment by Xander10alpha** [comment]
You can contact me about discord or what you want 
https://discord.gg/TSJtWX

**Comment by Xander10alpha** [comment]
Here you can contact me about Discord
https://discord.gg/FsdVH63
