### ISSUE TITLE
Hunting hut !

### ISSUE THREAD

**Issue by Lolasik011** [Sh0wdown/UnofficialCrusaderPatch#46]
It would be great if AI used hunting huts. But I know that it will not be effective on all maps. Although a good boost will be for the economy of AI.
Of course, you can make AI huts for hunters only as long as there are deers on the map.
Hunters with their arrows do the same damage as European archers, but will be killed with one shot :))

**Comment by Monsterfisch** [comment]
hunting huts can be added via the aiv editor for custom ai castles doubt it would be necessary to add in via the patcher otherwise it would be necessary to check for a bunch of things (custom code) to make the ai place and manage those buildings which would be a far greater task than probably worth it?

**Comment by Lolasik011** [comment]
I know that huts can be added through the AIV editor, but this is not as effective. Effectively, if  add this function in AI.

**Comment by Panbutt** [comment]
Tbh, the only thing I would adjust for the Hunter Huts is to make it so they're 'put to sleep' when there's no deer on the map. Right now AIs do not and so Hunter Huts just take up population when there are no deer.

**Comment by Lolasik011** [comment]
Yes, but you can make the AI in the absence of deer broke them. As an additional income of food.
