### ISSUE TITLE
comma or dot in the cfg file.

### ISSUE THREAD

**Issue by Krarilotus** [Sh0wdown/UnofficialCrusaderPatch#467]
@GRhin and i shared some pattcher settings via ucp.cfg.
Odd was, that his attack rate increase showed as 3 while i set itt to 0.3 (multtiplier)
Then we checked the cfg file, and his cfg file required a dot, while mine required a comma in between the 0.3 to be read as 0.3 which represents 30%.

We redownloaded the exe both and checked both how the fileformat was safed with no previous cfg. So from scratch. His exe safed the 0.3 with a dot while mine safed 0,3 with a comma.
We both use english language setting.

Maybe someone knows whats going on here?
HELP!

**Comment by J-T-de** [comment]
English language setting in the patcher or in the OS?

If the OS have different language settings, the reason might be, that German (and other languages(?)) usually use a "," as decimal separator, whereas most other languages use ".", so it might has its origin in some local settings.

**Comment by Krarilotus** [comment]
Hm but shouldnt the patcher have the text written by code himself? So it is compatibel between different OS settings?
So i would mark that as a bug in the patcher then, as it prevents from transferring data by the config.

**Comment by GRhin** [comment]
Yes, it can be displayed based on localization, however the software itself should read it the same. Otherwise having an external config file isnt very usefull. 
The reason we want to be able to share the config file is so we can play against AIs together, or for someone to set up a scenario to challenge others (e.g. Krarilotus's 4 character castle), the config is a part of making the scenario work.

**Comment by J-T-de** [comment]
Yes, it should definitely be compatible, it was more the question if the locale was the origin of this bug or something else.

**Comment by Sh0wdown** [comment]
@J-T-de is correct. Whether there is a comma or a dot depends on the OS' localization setting if nothing else is specified by the developer, which I forgot to do apparently. oops.

**Comment by Russianstory** [comment]
@Sh0wdown Tell me, are you still going to improve the game of Stronghold Cruzader 1? Will there be new interesting and useful changes in the game? When will we wait for them and what exactly will be done?
And have you considered those ideas that I wrote in my topic? I will be glad if you look and see. I think there are healthy and really useful thoughts for real improvement of the gameplay.

P, p. Thanks a lot for the semi-automatic controllability when creating siege weapons, and about the FINALLY treating doctor)))))))
-
Скажи пожалста ты ещё будешь улучшать игру Стронгхолд Крусадер 1 ? Будут ли новые интересные и полезные изменения в игре? Когда нам их ждать и что именно будет сделано?
И ещё не рассматривал ли ты те идеи что я писал у себя в теме? Буду рад если заглянешь и посмотришь. Думаю, там есть здрваые  и по-настоящему полезные мысли для реального улучшения игрового процесса.

П,с. оргомное спасибо за полуавтоматичскую управляемость при создании осадных орудий, и про НАКОНЕЦ таки лечащего лекаря )))))))

**Comment by Sh0wdown** [comment]
> @Sh0wdown Tell me, are you still going to improve the game of Stronghold Cruzader 1? Will there be new interesting and useful changes in the game? When will we wait for them and what exactly will be done?
> And have you considered those ideas that I wrote in my topic? I will be glad if you look and see. I think there are healthy and really useful thoughts for real improvement of the gameplay.
> 
> ## P, p. Thanks a lot for the semi-automatic controllability when creating siege weapons, and about the FINALLY treating doctor)))))))
> Скажи пожалста ты ещё будешь улучшать игру Стронгхолд Крусадер 1 ? Будут ли новые интересные и полезные изменения в игре? Когда нам их ждать и что именно будет сделано?
> И ещё не рассматривал ли ты те идеи что я писал у себя в теме? Буду рад если заглянешь и посмотришь. Думаю, там есть здрваые и по-настоящему полезные мысли для реального улучшения игрового процесса.
> 
> П,с. оргомное спасибо за полуавтоматичскую управляемость при создании осадных орудий, и про НАКОНЕЦ таки лечащего лекаря )))))))

I would love to, but I don't have much time at the moment. So I don't know when and what will come next.

**Comment by Russianstory** [comment]
Man, I myself have been doing a mod about Russia since 2009 alone ... I don’t give up. And you do not quit. Return to Stronghold Crusader 1. PLEASE! Continue to improve the game. You really, really did. I play now only with the new mod. He is beautiful! Truth! Please do not drop the Crusader modding and please improve further! =)
-
Дружище я сам уже в одиночестве делаю мод про Русь с 2009 года.... не бросаю. И ты не бросай. Вернись к Стронгхолд Крестоносец 1. ПОЖАЛСТА! Продолжай работу над улучшением игры. У тебя реально, классно получилось. Я играю теперь только с новым модом. Он прекрасен! Правда! Прошу не бросай моддинг КРестоносца и прошу улучшай дальше! =)

**Comment by ByBurton** [comment]
Fixed thanks to @patel-nikhil !
