### ISSUE TITLE
Laddermen AI use.

### ISSUE THREAD

**Issue by Xebenkeck** [Sh0wdown/UnofficialCrusaderPatch#493]
Hey guys

In my testing I unintentionally found out something that could potentially be useful and potentially fixed.

The AI IS capable of using laddermen properly if two conditions are met. The first makes sense, the second I have to believe was unintentional on Firefly's part.

1st) The walls the laddermen go up to MUST either be attached to the keep itself, or have a staircase attached which allows access to the Lord. 
-This is because of pathfinding, plain and simple, the enemy must see a path to the enemy lord. 
-The keep is seen as one way down off a wall and the stairs are obviously another. 
-A gatehouse DOES NOT count as a pathway for the AI. So if your AIV's have a keep surrounded by walls that are only accessable by gatehouses, the AI will not send its MainATT Units nor its AttUnit2's to climb ladders, they will instead just try to bash the walls down.

2nd) Stupidly, if the AI who is attacking, like The Snake, HAS HIS OWN KEEP ENCLOSED, then he will not send his MainATTUnits nor his AttUnit2's to climb ladders, they will instead just try to bash the walls down.

In order to make The Snake use his units properly his own keep can't be enclosed, and all the AI's he is attacking must have staircases or attachment to the keep in order to send his units to climb them.

For someone like me, who created all my own AIV's I will be going back and putting staircases on all my castles for balance reasons now. So that AI's I create using laddermen actually use them.

One neat trick is to use the double drawbridge enclosed glitch (the one where you place two drawbridges facing each other, with access from the sides making the game think the keep is not enclosed, but when the drawbridges lift the keep gets enclosed) to design The Snake's castle's so that he can use laddermen.

The only other way AI units will climb a ladder is if units like Attunitengage are nearby and the enemy they see(they are in aggressive stance) is up a ladder on the wall or a tower. 
OR
Units in the attackunitmain/attackunit2 finish breaking down a wall(usually because multiple units are hitting the same piece of wall) they also are in aggresive stance at this time and may choose to attack an enemy up a ladder on the wall.
OR 
Units filling moats are out of moat to fill, also go into aggresive stance and may climb a ladder to attack units on the wall.

It would wonderful if you guys who know more about coding could find where this is and potentially correct it so that the attacking AI doesn't have to have an "open" keep in order to use laddermen properly.

**Comment by Xebenkeck** [comment]
It crossed my mind t test siege towers as well. I just didn't have the time to last night, I can because I'm just guessing that it would be the same.

Also yes only EArchers, Spearmen, Macemen, Pikemen can climb ladders. If you have swordsmen as the AttMain they will bash the walls as normal.

And I will get a pic of the drawbridge glitch when I get home tonight for you if your not aware of it.

**Comment by Xebenkeck** [comment]
![image](https://user-images.githubusercontent.com/59375270/72578001-5a572100-389a-11ea-8b17-d27eb6fbd77d.png)
 vs 
![image](https://user-images.githubusercontent.com/59375270/72578045-7d81d080-389a-11ea-962f-81e31d47d8d9.png)

Notice how in the second pic the enclosed symbol is on the minimap vs the first pic where the enclosed symbol is not there. This is the enclosed drawbridge glitch.

**Comment by LordHansCapon** [comment]
Regarding units not climbing laddermen, I have found the code part where it gets determined whether units should climb the laddermen or not, however, it is far more complex than I thought. Of course I could always force units to climb laddermen if they are available, but that made the melee units just not attack the walls at all and wait for laddermen to get in position.

Something is wrong with re-evaluating whether the AI has laddermen ready at walls or not, but I am close to solving this issue.

**Comment by J-T-de** [comment]
As far as I know, the problem is lies on two different parts:

1. One is the pathfinding as Xebenkeck mentions: if there is no way to the keep, the units don't climb.

2. Even if there is a path, the laddermen as part of the main force, attack the wall in the same time the melee units attack the wall. And while the main force is busy attacking the wall, they do not accept the path over the ladders, whereas if the walls are torn down, they immediately go for the lord. So really inconsistent behavior.

**Comment by Krarilotus** [comment]
@LordHansCapon nice work, but here is the real issue:
pathfinding in Stronghold Crusader. 
There are many wierd bugs related to that topic. I ll just list a few, maybe you came across those, when fixing the laddermen issue:

- workers are forced on entrences, that rotate clockwise around buildings, if their original entrance is obscured. This is specifically an issue, if an entrance is not connected to the 'outside world'.
-> it can happen, that for example the stockpile has one space next to it, which is optherwise not accessable. Then workers who want to access that stockpile dont work, as if the stockpile was empty, as the stockpile registers that as the default location to get goods from.
proposal for solving that: force entrances to look for pathfidning to ressources on initial setup by checking all 'connected' buildings and the building itself for pathfiding. Each building here would have to be handled individually. Also when moats/walls are build next to a building, they should always update their entrance, and not only if a whole side is covered with wall, which makes the building turn btw, and the entrance gets moved to the complete opposite side of that wall. That makes the roof go diagonal from then on. -> so there is already some algorthm in place, which could be used for that purpose and modified.
-> this is a huge change i guess, but it would solve most lag issues and most issues in general in the game related to pathfinding with workers, that get stuck.


- pathfinding gets only updated if an obtacle is hit or the destination is reached. That makes workers get stuck or even disappear. Which is frustrating. Sometimes they even get stuck on low stairs, in front of gates that are open and stuff like that, and stay there until they get killed or some gate gets closed/opened to update their pathing.
-> this should be fixable by giving workers either an update timer which checks for changed pathways every once in a while (could be heavy on the CPU side) or we could actually make some kind of path mapping system, where we would then map all paths that get taken currently, and if one gets updated, we would also update all paths that correlate with that path in the region that caused the update. I guess this is to difficult to implement? Or if it wasnt, it would take some work.



Now to the pathfinding and decision making of AI's:
The main issue for me is, that they just walk around walls and obstacles even if they would be faster destroying them.
-> to fix that, we would have to give Obstacles a different value than 'nonpathable' for units, as giving them some kind of HP value, which then can be used to solve the pathfinding equation.
We would solve the equation by simply checking if the destruction of set opstacles that obscures the way to the target destination would be faster than walking, and wollah, we just set the soldiers automatically into destruction mode and target that obstacle. They already have some kind of way to tell where the weakest point in an enemies castle is, in the case that there is no open pathway, which we could use here in the same way.

Next problem: If the enemies use gatehouses, units seem to not recognize open gates as 'nonpathable' objects, and aim to walk through them. This causes units to just walk around, and turning every time they reach a gate that gets closed before they can reach it.
-> instead there should be 2 behaviours: 1. for assassins: they should see gates as climbable objects, that they should just aim to climb right away, when it gets closed. (some assassins are already handled seperatly, i just wish they wouldnt turn around when a gate gets closed  and another pathway is still open.)
2. For normal soldiers, they should see gates as 'always closed' if they are not controlled by themselfs. So that they then evaluate them by their HP as destructable objects for pathfinding.

This is probably too difficult to work into assembler?
But i can keep my hopes :D
If you need any algorithmic help for these things or more inside knowledge about the pathfinding and its current expected behabviour, you can always ask me here or add me on discord to ask me directly. Discord: Krarilotus#6749

**Comment by LordHansCapon** [comment]
I find pathfinding exceptionally hard to modify, especially at the level you want. I think it is way too complex to make these changes in assembly.

But it is possible to setup a timer and update units and workers pathfinding regularly. Though I guess it would be a bit heavier on the CPU that's for sure.

@J-T-de That is exactly how the AI works. Can be easily seen in code aswell, as most of the stuff regarding pathfinding during siege is written pretty simply. However, its not the keep they are looking for as I found, its the King, if you wall in the king and leave your keep "exposed" while they have laddermen, they won't climb the laddermen as they have no path to the lord.

**Comment by Xebenkeck** [comment]
-The path-finding to the king/lord make sense. Why would a CPU tell its units to climb a wall where thee is possibly no other way down, or doesn't directly lead to the lord. This one isnt as important to fix its the other issue.

-The one that doesn't make sense is why their own keep(the attacker's) must be enclosed. If you have found a solution to that, then that alone makes the AI way better.

-I guess the other issue that would help is if you can get units to realize a closed gate is a pathway to the lord if you are on top of the wall because when they get onto the gatehouse they will take over it.

**Comment by LordHansCapon** [comment]
To be honest, I have never seen AI units climb walls, like ever. Not in vanilla, and not in UCP. Is it even working by default? Once I set some stuff in assembly, the units started to climb walls and all worked well, but I bet my head on it that I did not see AI units climb before.

**Comment by J-T-de** [comment]
> @J-T-de That is exactly how the AI works. Can be easily seen in code aswell, as most of the stuff regarding pathfinding during siege is written pretty simply. However, its not the keep they are looking for as I found, its the King, if you wall in the king and leave your keep "exposed" while they have laddermen, they won't climb the laddermen as they have no path to the lord.

Yeah, it makes sense that the are looking for the lord...

> To be honest, I have never seen AI units climb walls, like ever. Not in vanilla, and not in UCP. Is it even working by default? Once I set some stuff in assembly, the units started to climb walls and all worked well, but I bet my head on it that I did not see AI units climb before.

Well, only the snake uses laddermen, and if Xebenkeck is right with his new insight, i.e. "as soon as the keep is enclosed, no more using ladders", then there is a really low probability that one witnesses this.

Once I experimented with giving the pig siege towers. If I remember correctly, the maceman immediately used the siege tower if they had a path to the lord. Even though the keep of the pig was enclosed and the macemen were already attacking the walls (and damn, maceman yoloing around the walls was mad!).

**Comment by LordHansCapon** [comment]
Alright, I have taken control over snake and demolished his gates and walls right before he was attacking, and I can confirm that if the Snake's keep is enclosed, then he will NOT use laddermen. So you were right, I am looking into it as why would this ever happen.

**Comment by LordHansCapon** [comment]
@Xebenkeck @J-T-de @Krarilotus I have found the issue with laddermen not climbing ladders when AI is enclosed. I will be adding it as a fix in my fork of UCP.

**Comment by ByBurton** [comment]
![image](https://user-images.githubusercontent.com/25118004/72651190-f2303a00-3982-11ea-810d-f551189dcfa7.png)

Fixed thanks to @LordHansCapon

**Comment by ByBurton** [comment]
I'll actually reopen this, as there might be more things that can be solved.

**Comment by LordHansCapon** [comment]
@ByBurton Yes, gatehouses SHOULD count as a pathway for the AI. Interestingly enough, the pathfinding DOES use gatehouses, but the function which determines whether there is a reason to climb the ladders does not. Now that I found the function which determines that, I may be able to add gatehouses checks.

**Comment by ByBurton** [comment]
![image](https://user-image@LordHansCapon thubusercontent.com/25118004/72651552-edb85100-3983-11ea-9887-a6b9562614d9.png)

@LordHansCapon That would be epic. I always loved laddermen. And spearmen are my all time favourite unit (the only unit that can kick walls down). It would also enable an AI I made that focuses on laddermen, spearmen and archers.

**Comment by LordHansCapon** [comment]
@ByBurton Wow, Richard is in trouble.

**Comment by Krarilotus** [comment]
this is epic :D

Should we make another issue for the pathfinding with open gates?
I feel like its seperate topic :)

so we will probably not be able to fix the issue, that AI's always take open pathways?
But could we fix the issue, that AI sees Gatehouses of enemies that are currently open but not under their control as a pathway into the enemy castle?

I ll pin a video demonstrating this issue here soon. One of the AI's in the last AI Contest i hosted abuses this issue alot, which makes its defense broken, while having not a single tower.

**Comment by Xebenkeck** [comment]
Awesome guys.

The Snake and other created AI lords will be so much more potent now.

So for someone like me who doesn't know how to change the .exe, or add lines of code,  I just have to wait for a official release witht his change for this to work for me right?

**Comment by Lolasik011** [comment]
@ByBurton @LordHansCapon  How to download a new patch ? Thank you!

**Comment by LordHansCapon** [comment]
@Lolasik011 Once @Sh0wdown creates a new release, you can download it, or you could just build the project yourself and do so. Or maybe I could upload it somewhere and share the link. Because I can not upload it here, it is too big to share it in here.

**Comment by Lolasik011** [comment]
@LordHansCapon Google drive ...

**Comment by Heroesflorian** [comment]
Working laddermen, finally after nearly 2 decades?! :O Noiice!

> But could we fix the issue, that AI sees Gatehouses of enemies that are currently open but not under their control as a pathway into the enemy castle?

@Krarilotus Oh yeah... and this issue becomes even larger when moat/drawbridges are involved... you know, non-digging units run around half of the castle towards a drawbridge, drawbridge closes up, units stand there brainlessly until they're dead, drawbridge opens, more units start running towards it...

**Comment by GRhin** [comment]
Can be closed with new release
