### ISSUE TITLE
Unit health changes not working?

### ISSUE THREAD

**Issue by GRhin** [Sh0wdown/UnofficialCrusaderPatch#520]
So I could just be an idiot.
I searched for array of bytes in cheat engine on an unmodified Stronghold Crusader, and am unable to find the AoB for the unit changes.
As an idiot test, i searched the AoB @LordHansCapon posted in his #488 contributer tutorial (13 00 00 00 11 00 00 00 15 00 00 00 12 00 00 00 14 00 00 00 16 00 00 00 17 00 00 00 18 00 00 00) and found it no problem. 
But when i search the AoB in the codeblocks for u_arabwall.block (01 1C 1B 1A 19 19 1A 1B 1C 01 02 03 04 04 05 06 07 08 09 0A 0B 0B 0C 0D 0D 0E 0E 0F 10 11 12 12) i find nothing. This has been the same for all the u_<unit><unit>.block files i have tested, and i have tested most of them.

Have I done something wrong? or are these changes not actually working?

**Comment by J-T-de** [comment]
Can confirm, some of the u_*.block files are not valid AOBs. Tested for 1.4.1 and 1.3.0... What the hell happened there?

**Comment by LordHansCapon** [comment]
@GRhin Enable CopyOnWrite, then search again. If you can't find it via Cheat Engine, I advise getting a hex editor such as [HxD](https://mh-nexus.de/en/hxd/). You open the "Stronghold Crusader.exe" then search for hex values.

![hxd](https://user-images.githubusercontent.com/59705872/73679357-8952fc80-46ba-11ea-81da-56be6f6e4607.PNG)

![hxd](https://user-images.githubusercontent.com/59705872/73679688-2f066b80-46bb-11ea-87c3-9177668c569d.PNG)

Then after finding the bytes, you can note down the address, in the picture above the starting address is **00555BC8**. This is the static address in the exe, but when its loaded to memory, in Stronghold Crusader's case, **00400000** will be added to the address so it will be **00955BC8** at runtime. If you can't find your AOB is the exe, that is probably because it was allocated at runtime. Such as maps loaded from the maps folder, and stuff like that.

Sorry if my explanation is not clear enough, when I get some time I will write more to the contributor tutorial... a much more less gibberish than I wrote here. But in the meantime, I hope this comment helped a bit.

**Comment by J-T-de** [comment]
Thanks for the clarification. I guessed the entire block should be loaded on runtime, but apparently, it is not...

**Comment by GRhin** [comment]
thanks LordHansCapon, CopyOnWrite fixed it. 
This is unrelated to the core of this thread (which i suppose could be closed now) but once i found that AoB I went to find it in ida freeware disassembler, unfortunately it seems the freeware only disassembled the first little bit, and didnt disassemble that part. I want to be able to browse the machine code to find the health blocks for other units, or other characteristics of units (e.g. speed). 
Is there something i can do to get the rest of the file disassembled?
