### ISSUE TITLE
AICE Editor not downloadable. 

### ISSUE THREAD

**Issue by KingCaliph** [Sh0wdown/UnofficialCrusaderPatch#527]
Now I may be missing something, or just plain stupid, but I have been trying to get ByBurton's AICE and I can't. All AICE links lead me to an error screen. 

If this "issue" post is too unrelated to the idea of this forum, then someone please let me know and I will take it down immediately. I was just looking for a solution to this problem.

**Comment by Starshine575** [comment]
@KingCaliph I am a bit confused:
Are you talking about the Editor itself or only the AICs of ByBurton? 🤔😅

**Comment by KingCaliph** [comment]
@Starshine575 I am talking about the editor itself, I am under the impression that ByBurton created it. 

https://github.com/Sh0wdown/UnofficialCrusaderPatch/wiki/AIC-Editing-Tutorial  This is where I went to download the editor (if you scroll down to "Editing AIC Files", you will find the link) but when I do, I get an error screen. Sorry if wasn't being clear or if I wasn't using the correct "jargon". I've played the game for years, and I just recently found this forum along with all these awesome mods/patches.

**Comment by Krarilotus** [comment]
I would say, the AIC Editor has been put on ice for now and is kind of more an idea for a fully finished AIC sheet in the future. You can tho just follow the wiki on AI personality to get to know the values or watch my youtube guides on how to create AI's with modifying the AIC sheet. Then you edit the AIC with some normal texteditor like notepad++. Search youtube for AI design tutorial stronghold Crusader AIC and you will find some content on that. Hope i could help, if you want i can post the videos later, in case you couldnt find them.

**Comment by ByBurton** [comment]
I've stopped developing it, though I may go back to it once we've found out all variables, if we ever do.
The editor I had created was very annoying to use and that is not what I had in mind when developing it.
I wanted to have a very quick way to adjust everything with a very easy to read interface.
So that it would be easier than just editing the variables in the editor.
(I also wanted to have useful options in that you can enable / disable...)
I'll close this issue for now as in fact there is no editor anymore that works with the current aic format.
