### ISSUE TITLE
One or two more mines/quarries for some AI lords.

### ISSUE THREAD

**Issue by PitchNeeded** [Sh0wdown/UnofficialCrusaderPatch#63]
Some lords with the original castles can tend to run out of gold too easily as they use expensive troops (the Arabian lords and Wolf particularly). Therefore I think one or two additional iron or stone mines for some of the AI lords that use more expensive troops would be excellent as an additional source of income for them, and also means they can benefit from large deposits of iron or stone near their castle better. Even Sultan could do with another quarry, he has enough troops to defend three. Of course more quarries or mines means more population and it needs to be checked that the ale producing AI do not lose their +8 bonus though on the vanilla castles, and the same with the religion-using AI (and additional mines would be also better I think for the ale or religion AI than additional quarries as they use less population than quarries).

**Comment by Panbutt** [comment]
Marshal is a huge victim of this. When he buys in weapons, it dries out his economy very quickly. I think he should have at least 3 quarries, keeping him competitive with Sheriff and Wazir. I also think an extra Iron Mine and some Orchards would benefit him a lot.

**Comment by ByBurton** [comment]
I disagree with the quarries.

**Comment by Lolasik011** [comment]
If it raises their economy for the better, then I’m for

**Comment by PitchNeeded** [comment]
> If it raises their economy for the better, then I’m for

The likes of Abbot, Sheriff and Frederick are probably fine as they are, as their economy seems good enough as it is, but the rest of the AI's would benefit from 1 or 2 more iron mines (or just an additional quarry for Rat, Snake and Sultan who don't create iron mines). I watched an AI only match between 8 players on a map (4 vs 4) with decent resource supplies and I noticed that quite a bit of the iron deposits still go unused, the stone supplies were used better because stone quarries are bigger.

**Comment by Monsterfisch** [comment]
Instead of upping their economy to all be the same roughly. In my eyes, it would be better to make ai trading with each other possible. 
That way you could have it so those ais that don't produce strong troops but have raging eco can support their allies with goods to get their siege force going faster. particularly with the abbot which in return could ask for reinforcements more frequently as he has a weaker def in terms of unitstrength

**Comment by Rakso69** [comment]
@Monsterfisch Good idea, but that would work only if the AI had any ally in atleast a 1vs2 environement. If the game is in 1vs1 environment, then the AI would act as it is - not as much efficent in iron mines ratio to eco.
2 more iron mines for AI do not mean nothing, as long they're still leaving so many of it on the map unused, do that wouldn't be Overpowered, but can help them.

Anyway: the distance of an iron mine to the stockpile also matter. I think it would be wise to consider the ammount of build mines depending on the distance workers would need to walk across instead of only rise the ammount.(Perhaps that might be the main problem)

**Comment by PitchNeeded** [comment]
> Instead of upping their economy to all be the same roughly. In my eyes, it would be better to make ai trading with each other possible.

Why not have both though :D - alongside AIs trading with each other, it would still help the AI who use iron mines (with the exception of Sheriff who has enough at 6 iron mines) to have one or two iron mines more.

**Comment by LordDerMoff** [comment]
I strongly disagree with an higher amount of quarries or/and iron mines... The AI had flaws wich had been fixed quite well until now. And most of them really profited by those changes and are a lot better than before. Still it should always be considered if it doesn`t change them too much. If we start to overpower every AI they loose their unique character. The Sultan is a old pacifist and the Rat is still just some Rat. And it´s the same for the other AI Lords aswell. They just can`t be strong opponents. It wouldn`t fit with the lore... 2 Iron mines or quarries are really a lot. This would pimp the marshal from and strong but old and senil man to a furious teenager. If you really want to play with strong opponents, take the Wolf, give him a lot more money than you and a favorable castle and position - voilà! I would agree to make more ox tether, because it usually doesn't lack quarries but oxen for a better stone production. By the way, this is a way more AIV related topic than any topic considering the "exe." And those can even be made by newbies.

**Comment by PitchNeeded** [comment]
> I strongly disagree with an higher amount of quarries or/and iron mines... The AI had flaws wich had been fixed quite well until now. And most of them really profited by those changes and are a lot better than before. Still it should always be considered if it doesn`t change them too much. If we start to overpower every AI they loose their unique character. The Sultan is a old pacifist and the Rat is still just some Rat. And it´s the same for the other AI Lords aswell. They just can`t be strong opponents. It wouldn`t fit with the lore... 2 Iron mines or quarries are really a lot. This would pimp the marshal from strong but old and senil man to a furious teenager. If you really want to play with strong opponents, take the Wolf, give him a lot more money than you and a favorable castle and position - voilà! I would agree to make more ox tether, because it usually doesn't lack quarries but oxen for a better stone production. By the way, this is a way more AIV related topic than any topic considering the "exe." And those can even be made by newbies.

Yes OK maybe not Sultan or Rat then, but I still think the stronger Arabian lords Caliph, Nizar, Wazir, Emir and Saladin, who all use expensive troops could do with 1 or 2 more iron mines I think. They run out of gold too quickly on a 40000 gold start (unless they are in an excellent economic position on the map). And anyway the iron supplies are big enough on many maps for some more AI iron mines, so 1 or 2 more for the strong AIs that use expensive troops would be a good idea I think, less resources on the map would be wasted and unused.

**Comment by Monsterfisch** [comment]
I agree with LordDerMoff optimize the characters to the amount where they still are distinguishable as themselves which would also mean that ai lords that would make sense to have a stable economy to be buffed in that regard.
The problem I predict however is that the issue at hand oftentimes is rooted in the number of resources available on the map and the number of resources required to make a certain character viable some need more resources by default some less, which makes perfect sense as you wouldn't build a massive economy in the dryest badland there is kind of thinking here. That's why I would personally like to see the trading between ai lords as that can make it possible to have more interesting scenarios where the ais can snowball by providing teamplay instead of every ally for themselves. while making it so that the characters stay in character in matches set up to be "easier/themed".
What I could understand however is that it would make sense to buff the economy later in the game when the ai sends out larger waves of units which in result requires more money to maintain at a more or less constant rate. here one could argue that the rat would start building more quarries or maybe even a pitch or iron mine to get extra income but only very sparingly as he isn't a complete economic genius. So depending on the character, it would happen sooner or later just not immediately so you have more of a transition into a more stable late game. Hard to say how feasible to set up that would be however with the tools available.

**Comment by Lolasik011** [comment]
It will be true for all if the launcher is the economy at the user's choice.

**Comment by PitchNeeded** [comment]
> I agree with LordDerMoff optimize the characters to the amount where they still are distinguishable as themselves which would also mean that ai lords that would make sense to have a stable economy to be buffed in that regard.

OK here's my proposal then:

Caliph : +2 iron mines (he has a reasonably weak economy compared to the other strong Arabian AIs and even with negative fear factor boosts still needs two more I think)
Wazir +1 iron mine, Wolf +1 iron mine (these two have negative fear factor so just 1 more will make a big difference)
Emir +1 iron mine, Saladin: +1 iron mine (these already have a reasonable economy but could do with a small boost)
Nizar +1 quarry (he needs another quarry for more stone, he only has 1 quarry after all)
Phillip +1 quarry (he has no quarries at the minute)
Lionheart +1 iron mine, Marshall +1 iron mine (I guess they could do with one more so they don't have to buy in quite as many metal weapons)

**Comment by Flechador** [comment]
> OK here's my proposal then:
> Caliph : +2 iron mines (he has a reasonably weak economy compared to the other strong Arabian AIs and even with negative fear factor boosts still needs two more I think)
> Wazir +1 iron mine, Wolf +1 iron mine (these two have negative fear factor so just 1 more will make a big difference)
> Emir +1 iron mine, Saladin: +1 iron mine (these already have a reasonable economy but could do with a 
> small boost as they use expensive troops)
> Nizar +1 quarry (he needs another quarry for more stone, he only has 1 quarry after all)
> Phillip +1 quarry (he has no quarries at the minute)
> Lionheart +1 iron mine (I guess he could do with one more so they he doesn't have to buy in quite as many metal weapons)


Very Good! I agree. ;)

**Comment by Lolasik011** [comment]
@PitchNeeded  Good idea !

**Comment by Sh0wdown** [comment]
Closing this for duplicate issues. Please continue discussion here: https://github.com/Sh0wdown/UnofficialCrusaderPatch/issues/77
