### ISSUE TITLE
AI military tactics issue

### ISSUE THREAD

**Issue by Lolasik011** [Sh0wdown/UnofficialCrusaderPatch#68]
I noticed that even if the wolf has many warriors (400-500), it attacks in small clusters, until it breaks the wall or digs a ditch, if it is not pierced, the Wolf will leave the army to death or retreat to the castle. Conclusion even a small ditch can stop the troops of the Wolf.

**Comment by Lolasik011** [comment]
By the way, all AIs collect a lot of warriors near their quarries and iron mines thereby reducing the attack power on the enemy. Sometimes the number comes to 250 - 300 warriors.

**Comment by PitchNeeded** [comment]
Once Frederick has his moat up the other AIs struggle to effectively besiege them. They just put send a few at at a time to attack the front sub-castle and the rest just go on aggressive stance killing workers/soldiers outside his castle).

It's similar with AIs besieging Nizar too to some degree, but it is easier for them against Nizar in that a lot of damage can be done to his castle with only a few catapults, unlike with Frederick's castle.

**Comment by Lolasik011** [comment]
I noticed that the Sheriff is attacking very weakly. I do not know what it depends on. Maybe some kind of economic bug ?

**Comment by PitchNeeded** [comment]
> By the way, all AIs collect a lot of warriors near their quarries and iron mines thereby reducing the attack power on the enemy. Sometimes the number comes to 250 - 300 warriors.

That reminds me..... in an AI only match I was spectating today using the great new spectate feature, Emir sent a lot of Arabian swordsmen towards his enemy Pig but the problem was half of them were his raiding party he was sending simultaneously up to destroy Pig's farms and half was the proper the siege force, the siege force alone couldn't kill him (they did manage to do a little damage to the lord) but if he would have switched his raiding Arabian swordsmen to being part of his siege force, he would have killed Pig. It should definitively be changed if possible that where if there is a siege going on, any raiding party of the besieging player within a certain distance becomes part of the proper siege force.

**Comment by Rakso69** [comment]
In any case AI trying to destroy other AI granary, armoury and market, as well as of human player is pointless.

AI should go straight ahead to kill the lord if the keep is reachable, instead of being killed all around by the opponent ranged troops, instead of this stupid insist on destroying every building while doing so.
This way:
- AI besieging would took way less time, so another attack would be being prepared already.(I've noticed AI do not recruit troops for another siege unless the current one on realization isn't conceded)
- It's better to get rid of an other AI opponent already if possible instead of leaving him without any possibility to rebuild himself again as a wasted spot to launch another attack on him or leave him as easy 500(+) gold to other AIs.
- If the AI are very close to eachother, they should go straight ahead for kill in order to get more space and freedom by freeing itself from the annoying un-teamed neighbour.
- AI can aswell gain by so on both defense and offense. On defense: If the economy isn't focused by troops, but cata only, then the AI could survive longer, eventually being capable of prospering close to eachother instead of being doomed since the beginning cuz someone stronger is around. Killing workers is enough to make AI eco suffer from an efficent siege.

**Comment by PitchNeeded** [comment]
> It's better to get rid of an other AI opponent already if possible instead of leaving him without any possibility to rebuild himself again as a wasted spot to launch another attack on him or leave him as easy 500(+) gold to other AIs.

Yep this is a particular problem with Emir too, his big raiding parties of Arabian swordsmen can completely ruin another other AIs economy which is of course excellent but the downside is his raiding parties rarely tend to go for the lord, meaning other AIs can get an easy kill when Emir did most of the work. It would be good if it was changed so his raiding parties would go for the lord if the AI was weak enough (maybe if the AI being besieged was 'worried about the attack and entered the phase where they sleep their economic buildings to hire troops and send their 'panicking' message.

**Comment by PitchNeeded** [comment]
Btw, Lolasik, I think the title of this topic would be better as 'AI military tactics effectiveness'. :D

**Comment by Lolasik011** [comment]
I noticed that the Arab Lords are quickly recruiting an army and are left with good economics and the European Lods are recruiting meddling troops and staying with poor economics.

**Comment by Lolasik011** [comment]
@Sh0wdown I noticed that the Arab Lords are quickly recruiting an army and are left with good economics and the European Lods are recruiting meddling troops and staying with poor economics.
