### ISSUE TITLE
How to view AI rations and tax levels

### ISSUE THREAD

**Issue by PitchNeeded** [Sh0wdown/UnofficialCrusaderPatch#72]
I finally found out how to view the AI tax and ration levels. By accident, as I had saved and reloaded an AI after the visual glitch happened.

Simply save then reload an AI only game, and you can view these AI statistics, but it only works really once the AI castle is completed, if you do it too soon into a game the AI won't build their castle.

**Comment by ByBurton** [comment]
And how do you view it?! How does it look? Can you upload a screenshot?

**Comment by Lolasik011** [comment]
Need screenshot ...

**Comment by PitchNeeded** [comment]
> And how do you view it?! How does it look? Can you upload a screenshot?

It's just in the same place where the scribe with the scroll is and where you view your own tax levels and ration levels.

**Comment by Rakso69** [comment]
Mine Wolf AIV is mad, no doubt. lol :rofl: 
![obraz](https://user-images.githubusercontent.com/45049934/48904944-6dba5800-ee60-11e8-8745-59b77392781e.png)
![obraz](https://user-images.githubusercontent.com/45049934/48904963-7ca10a80-ee60-11e8-826a-66931bb71a19.png)

**Comment by Lolasik011** [comment]
0_0 immpresive!

**Comment by Rakso69** [comment]
@Lolasik. Nah I playtested vs all other AI lords 1vs1 on all gold settings possible. He owns them.

**Comment by Lolasik011** [comment]
@Rakso69 I still think he will lose. Because I have not seen more than one battle, except for your screenshots. Because I have not seen  battle, except for your screenshots. And he can only play on your map. Plus it is clearly being built for a long time.

**Comment by Rakso69** [comment]
@Lolasik011 We can say that he's on really early beta version. For now I'll wait for futher patch upgrades to work over him futher.
I agree with everything You said. I didn't made him compactible with more maps than this one, it's likely beacuse he has only one AIV file, no more.
Tbh he doesn't even enclose himself on maps where he's put in the middle, beacuse He doesn't have any wall on the side of the grass as you see, but that helps him when he's at the corners, cuz the game rotates him in such a way as presented above in order to "close his keep".
Right, surely I'd make his defense better if the AIV had more options & less limits. For now I can't think of anything beside that.
Would be difficult to burn him without break his walls, but that's a stage when everyone is capable of that, so it has no point. He has wall "blankets" in the everywhere instead of normal walls, so they're bigger and less likely is possible to shoot through these. Also the mills themselfs serve as a little cover for the buildings inside, beacuse they're so tall, that might block a balista's belt.
As far as I'm aware there are no more efficent strategies to fight against fire except for:
a) Build a small eco in overall, and tons of water pots.
b) surround the economy with the tallest watchtowers(expensive tho).
c) delete the buildings as fire asap they catch it, so they fire does not spread futher
- this one could be possible to do by AI, as it has superhuman multitask, but I'd say it's too much broken to implement on the patch imo, cuz any building whoom would catch fire would be immediatly deleted and build anew in a few seconds. :D
I agree that the economy also must be flexible, but AI doesn't put it into consideration, it just choses the most fitting castle instead of the most efficent economically one, as would be a castle with an economy capable of survival on an empty map without iron, stone, grass or anything for example.
Thanks for opinion. Cheers.

**Comment by PitchNeeded** [comment]
> as would be a castle with an economy capable of survival on an empty map without iron, stone, grass or anything for example.

Abbot could probably survive on a map with no resources with his vanilla castle (although maybe not with the lower gold starts though).

**Comment by Lolasik011** [comment]
@Rakso69 Do not worry, everything is ahead. You can make the perfect AI castle. I will wait for the castle to come out. Of course, if you share it :)

**Comment by Rakso69** [comment]
@Lolasik011 Oh. I recall why I didn't gave him the watch towers walls against fire balistas actually.
That's right! AI doesn't repair towers. That's also the reason for what I've surrounded the Large Towers with high wall blankets. Cuz he can repair these, so the towers could keep on hold longer against catapults barrage.

**Comment by Sh0wdown** [comment]
Yes, loading a save might do that. I will probably add it as a feature too in the next version.

**Comment by Heroesflorian** [comment]
By the way, sorry for being late to the party but this is "old news" so to say... one could just save a regular game, rename the "someName.sav" save file to "someName.map", place it in the maps folder and load it up in the editor. 
Then, in the editor one can inspect rations, taxes, etc. for all players on that savegame.
