### ISSUE TITLE
AI can be slow to rebuild quarries

### ISSUE THREAD

**Issue by PitchNeeded** [Sh0wdown/UnofficialCrusaderPatch#80]
I have noticed that the AI are slow to rebuild or sometimes don't rebuild some of their quarries if destroyed by an enemy, if they don't have wood in their stockpile. Even if they have enough other goods (such as loads of stone in their stockpile) to sell to buy wood.

Was watching an AI only match there, Phillip destroyed two of Emir's quarries with knights and as he didn't have any wood in his stockpile, Emir didn't rebuild them despite having loads of stone in his stockpile to sell to buy wood, so he only had two quarries in the big patch of stone near his castle instead of four from then on in the match.

I know Sultan is generally quick to rebuild his quarries, so maybe this only happens with AI's with big economies. It would be good though if the AI could buy in wood to rebuild quarries quicker than they they currently do, if they have the resources to sell to buy the wood (obviously they should still prioritize buying wood to rebuild a destroyed granary, marketplace or mercenary post over buying it to rebuild quarries)

**Comment by Sh0wdown** [comment]
I also noticed this. The AI seems to not buy much would for buildings after the initial build-up phase.

**Comment by PitchNeeded** [comment]
> I also noticed this. The AI seems to not buy much wood for buildings after the initial build-up phase.

Yeah it definitively needs to changed, so the AI can rebuild destroyed outside economic buildings such as farms, quarries and mines faster. Buying in 20 wood to replace a quarry is quite inexpensive too.

But of course any changes need to be play-tested to ensure the AI can still buy wood to rebuild destroyed castle buildings too.

**Comment by Heroesflorian** [comment]
One thing I also noticed is that the AI sometimes "try to" buy wood, but only buy exactly the missing amount - e.g. with 7 wood in stock, they buy 13 additional wood to have a total of 20 for the quarry. 
If they then also notice a missing woodcutter hut, they'll spend 3 wood on the woodcutter, then be left without enough wood for the quarry once more... with some fought-over woods and/or farmlands, this can repeat quite some times until the (in comparison) expensive quarry or iron mine eventually "gets through". 

Another potential issue: 20 wood in stockpile, 1 fletcher takes 1 wood, 19 wood in stockpile... shortly after, the AI notices "oh, 1 wood missing!", buys 1 more wood, and then the next fletcher comes by... :S 

One reason why Sultan is less affected: He has pretty much only quarries and woodcutters, no farms or a lot of other less-expensive wooden buildings that could "distract" him from replacing more expensive stuff like quarries. 
And his woodcutters are many, causing him to often have excess wood beyond need, so he has more than enough wood stockpiled at any time (as long as there's some trees on the map). 

---

A similar phenomenon can, by the way, be observed for stone as well: Sometimes the AI buys just enough stones to have e.g. 40 in stockpile for a big round tower, then repair a small section of wall for 5 stones, then notice they again lack stone for the round tower, buy 5 more stones, in between build a small gatehouse for 10 stones, then some more walls... then buy 20 more stones, spend more stone... and then eventually, hopefully, have 40 stones in stockpile for long enough to actually place their round tower. 
Again, having income from production buildings - in that case quarries / ox tethers - helps, to build excess stone reserves beyond the 40 needed, in order to leave "room for error" / building wall sections before placing a tower without having to constantly buy and miss...

**Comment by Sh0wdown** [comment]
The next release will increase the wood-amount the AI buys for each building by 2. This should prevent the thieving fletchers from taking a building material.

**Comment by Heroesflorian** [comment]
> The next release will increase the wood-amount the AI buys for each building by 2. This should prevent the thieving fletchers from taking away building material.

@Sh0wdown Is something similar planned for stone (for towers/gates) as well? Or do you think that would be more harmful than useful considering higher per-unit costs for stone?
