### ISSUE TITLE
More siege weapons for AI

### ISSUE THREAD

**Issue by Lolasik011** [Sh0wdown/UnofficialCrusaderPatch#82]
I think the AI must use siege towers and shields. This will complicate the game vs AI. I think that this ability is in AI, it just does not use. I saw how the AI uses siege towers and shields in Siege Missions.In free construction, he also uses shields and siege towers.

**Comment by PitchNeeded** [comment]
I would like to see the use of portable shields on towers, Wolf and Frederick in particular would be very hard to siege with those.

And on the subject of more siege weapons for AIs, I think Emir, Nizar, Pig and Wazir need to be given ballistas on some of their big towers that they aren't using for ballista/mangonels on in the **improved vanilla castles** part of the patch. Maybe Pig can have a mangonel too as it would fit with his brutal personality. Also find some way to give Frederick a ballista in the vanilla AIV's although that would be much harder. I know I could do it myself with the AIVs easily for personal use, but it would be nice to make it 'official' that these lords now use their towers better so that in Udwin's excellent videos of his AI vs AI battles we can see it happening. :smile:

**Comment by Sh0wdown** [comment]
I can try to just add them, but as I said in another thread, if the AI does not know how to use them it's useless because I cannot change that easily.

**Comment by PitchNeeded** [comment]
> I can try to just add them, but as I said in another thread, if the AI doesn't already know what to do with them it's useless because I cannot change that easily.

I didn't think you could add portable shields to towers in the AIV editor.....but maybe it is possible (although i don't think the AI would use them).
