### ISSUE TITLE
AI Castles for the future

### ISSUE THREAD

**Issue by Mizo5119** [Sh0wdown/UnofficialCrusaderPatch#99]
With 2.06 having the option to disable the AI from putting their production buildings on *sleep*, wouldn't this mean we can freely improve all AI castles such as giving Lords better eco/bread production?

That's just a thought.

**Comment by Lolasik011** [comment]
Not bad idea

**Comment by Panbutt** [comment]
I had the thought too. There's still the issue of AIs buying and instantly selling resources they don't normally use. Pitch being the best example. Put pitch on say, one of Pig's castles and he will dig himself into a hole from buying and selling so much pitch for infinite.

**Comment by Heroesflorian** [comment]
Also, just because the AI doesn't put everything to sleep immediately does NOT mean that the economy scales up easily. 

If the AI has no wheat or flour (and does not have tons of gold reserves for buying the resources right away either), this will still mean that a large bunch of millers / bakers are waiting for resources, doing nothing and consuming food/beer nonetheless. 
And when low on gold, pretty much any AI character prioritizes recruiting troops over buying raw materials to keep production chains going. 

So what does the fix for the AI's overly aggressive setting-everything-to-sleep-policy do? It improves the worst case endless cycle of wasting resources, but it does not fix general economic stupidity of the AI. Also, as @Panbutt already mentioned, it does not mean that you could now give e.g. inns to Richard: He will still not build hops farms, and even if he would, he'd sell hops immediately, and beer too, and never buy those resources either.

**Comment by Heroesflorian** [comment]
And another remark: With custom AIVs, one can generally try to increase in-castle economy of any AI, sure. But that comes at a cost: More expensive to set up, more space needed, probably harder to defend, possibly more susceptible to fire (unless you go the extra mile to take measures against that, which usually results at least in more space demand and higher population from additional wells). 
Thus, for many AI characters, the "usability" of castles with larger economy is questionable and must be finetuned and tested on a case-by-case basis.
